pause:
  name: Pause
  description: Pauses downloads.
resume:
  name: Resume
  description: Resumes downloads.
set_speed:
  name: Set speed
  description: Sets the download speed limit.
  fields:
    speed:
      name: Speed
      description: Speed limit. If specified as a number with no units, will be interpreted as a percent. If units are provided (e.g., 500K) will be interpreted absolutely.
      example: 100
      default: 100
      selector:
        text:
