- id: '1507434167220'
  alias: Coffee Maker On
  trigger:
  - platform: time
    at: '07:00:00'
  - platform: time
    at: '08:00:00'
  - platform: time
    at: '07:15:00'
  - platform: time
    at: '12:00:00'
  - platform: time
    at: '19:00:00'
  condition:
    condition: or
    conditions:
    - condition: template
      value_template: '{{ now().strftime(''%H:%M'') == ''07:00'' and now().weekday()
        < 5 }}'
    - condition: template
      value_template: '{{ now().strftime(''%H:%M'') == ''08:00'' and now().weekday()
        >= 5 }}'
    - condition: template
      value_template: '{{ now().strftime(''%H:%M'') == ''07:15'' and ((as_timestamp(now())
        - as_timestamp(''2017-09-24 00:00:00'')) / 86400)|int % 28 == 0 }}'
    - condition: template
      value_template: '{{ now().strftime(''%H:%M'') == ''12:00'' and ((as_timestamp(now())
        - as_timestamp(''2017-09-24 00:00:00'')) / 86400)|int % 28 == 0 }}'
    - condition: template
      value_template: '{{ now().strftime(''%H:%M'') == ''19:00'' }}'
  action:
  - service: switch.turn_on
    data:
      entity_id: switch.sonoff12914
- id: '1507434167221'
  alias: Coffee Maker Off
  initial_state: 'on'
  trigger:
  - platform: time
    at: '08:30:00'
  - platform: time
    at: '14:00:00'
  - platform: time
    at: '16:00:00'
  - platform: time
    at: '22:00:00'
  condition:
    condition: or
    conditions:
    - condition: template
      value_template: '{{ now().strftime(''%H:%M'') == ''08:30'' and ((as_timestamp(now())
        - as_timestamp(''2017-09-24 00:00:00'')) / 86400)|int % 28 == 0 }}'
    - condition: template
      value_template: '{{ now().strftime(''%H:%M'') == ''14:00'' and now().weekday()
        < 5 }}'
    - condition: template
      value_template: '{{ now().strftime(''%H:%M'') == ''16:00'' }}'
    - condition: template
      value_template: '{{ now().strftime(''%H:%M'') == ''22:00'' }}'
  action:
  - service: switch.turn_off
    data:
      entity_id: switch.sonoff12914
- id: '1505977024304'
  alias: Turn Lounge Light On Elevation < 25° & after 4PM
  trigger:
  - platform: numeric_state
    below: 25
    entity_id: sun.sun
    value_template: '{{ state.attributes.elevation }}'
  - platform: time
    at: '16:00:00'
  condition:
  - condition: time
    after: '16:00:00'
    before: '18:00:00'
  - condition: template
    value_template: '{{states.sun.sun.attributes.elevation < 25}}'
  action:
  - service: light.turn_on
    data:
      brightness_pct: 75
      entity_id: light.lounge
      kelvin: 3100
- id: '1523937971401'
  alias: Toothbrush On
  trigger:
  - platform: time
    at: '08:00:00'
  condition: []
  action:
  - service: switch.turn_on
    data:
      entity_id: switch.sonoff23110
- id: '1523938046054'
  alias: Toothbrush Off
  initial_state: 'on'
  trigger:
  - platform: time
    at: '21:00:00'
  - entity_id: switch.sonoff23110
    from: 'off'
    platform: state
    to: 'on'
  condition:
    condition: or
    conditions:
    - condition: time
      after: '21:00:00'
      before: '00:00:00'
    - condition: time
      after: '00:00:00'
      before: '08:00:00'
  action:
  - service: switch.turn_off
    data:
      entity_id: switch.sonoff23110
- id: '1519082437913'
  alias: Make Snapshot & Copy Backups to Dropbox
  initial_state: 'on'
  trigger:
  - platform: time
    at: '03:00:00'
  condition: []
  action:
  - service: hassio.snapshot_full
    data_template:
      name: Automated Backup {{ now().strftime('%Y-%m-%d') }}
  - service: notify.notify
    data_template:
      message: Created backup named "Automated Backup {{ now().strftime('%Y-%m-%d')
        }}"
  - delay: '01:00:00'
  - service: hassio.addon_stdin
    data_template:
      addon: 7be23ff5_dropbox_sync
      input:
        command: upload
  - service: notify.notify
    data_template:
      message: Copied all new backups to Dropbox
- id: '1532478833426'
  alias: Lights Off Failsafe
  initial_state: 'on'
  trigger:
  - platform: state
    from: 'on'
    to: 'off'
    entity_id: light.lounge, light.dining, light.desk, light.office
  condition: []
  action:
  - delay: '00:00:02'
  - service: light.turn_off
    data_template:
      entity_id: '{%- if (as_timestamp(now()) - as_timestamp(states.light.lounge.last_changed)
        < 5) and (as_timestamp(now()) - as_timestamp(states.light.desk.last_changed)
        < 5) -%} light.lounge, light.desk {%- elif (as_timestamp(now()) - as_timestamp(states.light.office.last_changed)
        < 5) and (as_timestamp(now()) - as_timestamp(states.light.desk.last_changed)
        < 5) -%} light.office, light.desk {%- elif (as_timestamp(now()) - as_timestamp(states.light.desk.last_changed)
        < 5) -%} light.desk {%- elif (as_timestamp(now()) - as_timestamp(states.light.office.last_changed)
        < 5) -%} light.office {%- elif (as_timestamp(now()) - as_timestamp(states.light.lounge.last_changed)
        < 5) -%} light.lounge {%- else -%} light.dining {%- endif -%}'
  - delay: '00:00:02'
  - service: light.turn_off
    data_template:
      entity_id: '{%- if (as_timestamp(now()) - as_timestamp(states.light.lounge.last_changed)
        < 10) and (as_timestamp(now()) - as_timestamp(states.light.desk.last_changed)
        < 10) -%} light.lounge, light.desk {%- elif (as_timestamp(now()) - as_timestamp(states.light.office.last_changed)
        < 10) and (as_timestamp(now()) - as_timestamp(states.light.desk.last_changed)
        < 10) -%} light.office, light.desk {%- elif (as_timestamp(now()) - as_timestamp(states.light.desk.last_changed)
        < 10) -%} light.desk {%- elif (as_timestamp(now()) - as_timestamp(states.light.office.last_changed)
        < 10) -%} light.office {%- elif (as_timestamp(now()) - as_timestamp(states.light.lounge.last_changed)
        < 10) -%} light.lounge {%- else -%} light.dining {%- endif -%}'
- id: '1532478833427'
  alias: Lights On Failsafe
  initial_state: 'on'
  trigger:
  - platform: state
    from: 'off'
    to: 'on'
    entity_id: light.lounge, light.dining, light.desk, light.office
  condition: []
  action:
  - delay: '00:00:02'
  - service: light.turn_on
    data_template:
      entity_id: '{%- if (as_timestamp(now()) - as_timestamp(states.light.lounge.last_changed)
        < 5) and (as_timestamp(now()) - as_timestamp(states.light.desk.last_changed)
        < 5) -%} light.lounge, light.desk {%- elif (as_timestamp(now()) - as_timestamp(states.light.office.last_changed)
        < 5) and (as_timestamp(now()) - as_timestamp(states.light.desk.last_changed)
        < 5) -%} light.office, light.desk {%- elif (as_timestamp(now()) - as_timestamp(states.light.desk.last_changed)
        < 5) -%} light.desk {%- elif (as_timestamp(now()) - as_timestamp(states.light.office.last_changed)
        < 5) -%} light.office {%- elif (as_timestamp(now()) - as_timestamp(states.light.lounge.last_changed)
        < 5) -%} light.lounge {%- else -%} light.dining {%- endif -%}'
      brightness_pct: 75
      kelvin: 3100
  - delay: '00:00:05'
  - service: light.turn_on
    data_template:
      entity_id: '{%- if (as_timestamp(now()) - as_timestamp(states.light.lounge.last_changed)
        < 10) and (as_timestamp(now()) - as_timestamp(states.light.desk.last_changed)
        < 10) -%} light.lounge, light.desk {%- elif (as_timestamp(now()) - as_timestamp(states.light.office.last_changed)
        < 10) and (as_timestamp(now()) - as_timestamp(states.light.desk.last_changed)
        < 10) -%} light.office, light.desk {%- elif (as_timestamp(now()) - as_timestamp(states.light.desk.last_changed)
        < 10) -%} light.desk {%- elif (as_timestamp(now()) - as_timestamp(states.light.office.last_changed)
        < 10) -%} light.office {%- elif (as_timestamp(now()) - as_timestamp(states.light.lounge.last_changed)
        < 10) -%} light.lounge {%- else -%} light.dining {%- endif -%}'
      brightness_pct: 75
      kelvin: 3100
- id: 'homeawayinpboolturnon'
  alias: Home and Away On
  initial_state: 'on'
  trigger:
  - entity_id: input_boolean.homeandawayauto
    from: 'off'
    platform: state
    to: 'on'
  action:
  - service: automation.turn_on
    data:
      entity_id: group.homeaway
- id: 'homeawayinpboolturnoff'
  alias: Home and Away Off
  initial_state: 'on'
  trigger:
  - entity_id: input_boolean.homeandawayauto
    from: 'on'
    platform: state
    to: 'off'
  action:
  - service: automation.turn_off
    data:
      entity_id: group.homeaway
- id: 'sonoff_firmware_installed'
  alias: Sonoff Firmware Installed
  trigger:
  - at: '00:00:00'
    platform: time
  - at: '12:00:00'
    platform: time
  - event: start
    platform: homeassistant
  action:
  - data:
      payload: '2'
      topic: sonoff1/cmnd/status
    service: mqtt.publish
  - data:
      payload: '2'
      topic: sonoff2/cmnd/status
    service: mqtt.publish
  - data:
      payload: '2'
      topic: sonoff5/cmnd/status
    service: mqtt.publish
  initial_state: 'on'
- id: '1532478833428'
  alias: Power State Sonoff on HA Start-Up
  trigger:
  - event: start
    platform: homeassistant
  action:
  - data:
      payload: ''
      topic: cmnd/sonoffs/state
    service: mqtt.publish
  - data:
      payload: ''
      topic: cmnd/sonoffs/power1
    service: mqtt.publish
  - data:
      payload: ''
      topic: cmnd/sonoffs/power2
    service: mqtt.publish
  - data:
      payload: ''
      topic: cmnd/sonoffs/Power3
    service: mqtt.publish
  - data:
      payload: ''
      topic: cmnd/sonoffs/power4
    service: mqtt.publish
  initial_state: 'on'
- id: 'SonoffMQTTAuto'
  alias: Enable MQTT discovery for all devices
  initial_state: 'on'
  trigger:
  - platform: homeassistant
    event: start
  action:
  - service: mqtt.publish
    data:
      topic: cmnd/sonoffs/SetOption19
      payload: '1'
  - service: mqtt.publish
    data:
      topic: cmnd/sonoffs/SetOption55
      payload: '1'
