homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret my_latitude
  longitude: !secret my_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret my_elevation
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: !secret my_timezone
  # Customization file
  customize: !include customize.yaml
  # Fuel Monitor, System Monitor, Sun, Moon, Transport Weather & Updates Packages
  packages: !include_dir_named packages
  # LimitlessLED
  customize_domain:
    light:
      assumed_state: false
  auth_mfa_modules:
    - type: notify
    - type: totp

# Python
# python_script:

# Map
map:

# Show links to resources in log and frontend
# introduction:

# Enables the frontend
frontend:
  javascript_version: latest

# HTML5 Push Notifications
notify:
  - name: html5_notify
    platform: html5
    gcm_api_key: !secret gcm_api
    gcm_sender_id: !secret gcm_sender

# Enables configuration UI
config:

http:
  # Uncomment this to add a password (recommended!)
  # api_password: !secret http_password
  # ssl_certificate: /ssl/fullchain.pem
  # ssl_key: /ssl/privkey.pem
  # trusted_networks:
  #   - !secret trusted_network
  ip_ban_enabled: True
  login_attempts_threshold: 5
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  base_url: !secret base_http_url

# iFrame Configurator, Terminal, Tasmoadmin & MDI Icon Files
panel_iframe:
  configurator:
    title: Configurator
    icon: mdi:wrench
    url: !secret configurator
  ide:
    title: IDE
    icon: mdi:code-braces
    url: !secret ide-cloud9    
  portainer:
    title: Portainer
    icon: mdi:docker
    url: !secret portainer
  terminal:
    title: Terminal
    icon: mdi:console
    url: !secret terminal
  tasmoadmin:
    title: Tasmo Admin
    icon: mdi:lightbulb-on
    url: !secret tasmoadmin
  logviewer:
    title: Log Viewer
    icon: mdi:script
    url: !secret logviewer
  mdiindex:
    title: MDI Icon Index
    icon: mdi:vector-square
    url: https://cdn.rawgit.com/james-fry/home-assistant-mdi/efd95d7a/home-assistant-mdi.html

# Recorder
recorder:
  db_url: !secret mariadburl
  purge_interval: 1
  purge_keep_days: 7

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:
  enable:
    - dlna_dmr

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Sensors
sensor:

# Certificate LetsEncrypt
  - platform: cert_expiry
    host: !secret my_letsencrypt
    port: !secret certificate_port
          
# Sonarr
  - platform: sonarr
    api_key: !secret my_sonarr_api
    host: !secret my_sonarr_host
    port: !secret my_sonarr_port
    monitored_conditions:
      - series
      - upcoming
      - wanted
      - queue
      - commands
    days: 2
  - platform: sonarr_upcoming_media
    api_key: !secret my_sonarr_api
    host: !secret my_sonarr_host
    port: !secret my_sonarr_port
    days: 14
    ssl: false
  - platform: radarr_upcoming_media
    api_key: !secret my_radarr_api
    host: !secret my_radarr_host
    port: !secret my_radarr_port
    days: 100
    ssl: false
    theaters: true

# Artisan Software Version
# Getting Artisan version from JSON
  - platform: rest
    resource: https://api.github.com/repos/artisan-roaster-scope/artisan/releases/latest
    name: Artisan Software Version
    username: !secret githubuser
    password: !secret githubpass
    authentication: basic
    value_template: '{{ value_json.tag_name }}'
    headers:
      Accept: application/vnd.github.v3+json
      Content-Type: application/json
      User-Agent: Home Assistant REST sensor

# Tasmota Firmware
# Getting Firmware from JSON for Tasmota
  - platform: rest
    resource: https://api.github.com/repos/arendst/Sonoff-Tasmota/releases/latest
    name: Sonoff Firmware Version Available
    username: !secret githubuser
    password: !secret githubpass
    authentication: basic
    value_template: '{{ value_json.tag_name }}'
    headers:
      Accept: application/vnd.github.v3+json
      Content-Type: application/json
      User-Agent: Home Assistant REST sensor
  - platform: mqtt
    name: "Coffee Maker Firmware"
    state_topic: "stat/sonoff1/STATUS2"
    value_template: "v{{ value_json.StatusFWR.Version }}"
  - platform: mqtt
    name: "Toothbrush Firmware"
    state_topic: "stat/sonoff2/STATUS2"
    value_template: "v{{ value_json.StatusFWR.Version }}"
binary_sensor:
  - platform: template
    sensors:
      sonoff_update_available:
        value_template: >-
          {{ (states.sensor.sonoff_firmware_version_available.state > states.sensor.toothbrush_firmware.state) or (states.sensor.sonoff_firmware_version_available.state > states.sensor.coffee_maker_firmware.state)
              }}

# SABnzbd
sabnzbd:
  api_key: !secret sabnzbd_api
  host: !secret my_sab_host
  sensors:
    - current_status
    - speed
    - queue_size
    - queue_remaining
    - disk_size
    - disk_free
    - queue_count
    - day_size
    - week_size
    - month_size
    - total_size

# iOS Component
ios:

# Text to speech
tts:
  - platform: google

# IFTTT
ifttt:
  key: !secret ifttt_api

# Kodi
media_player:
  - platform: kodi
    host: !secret my_kodi_host
    enable_websocket: true

# Xiaomi & Sonoff Switches
switch:
  - platform: xiaomi_miio
    name: Home Assistant
    host: !secret homeassistant-ip
    token: !secret homeassistant-token
  - platform: xiaomi_miio
    name: VPN Router
    host: !secret vpnrouter-ip
    token: !secret vpnrouter-token
  - platform: mqtt
    name: "Coffee Maker"
    command_topic: "cmnd/sonoff1/power"
    state_topic: "stat/sonoff1/POWER"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    retain: false
  - platform: mqtt
    name: "Toothbrush"
    command_topic: "cmnd/sonoff2/power"
    state_topic: "stat/sonoff2/POWER"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    retain: false

# Wemo Switch
wemo:
  static:
    - !secret wemo_ip
# MQTT
mqtt:
  broker: core-mosquitto
  username: !secret mqtt_user_name
  password: !secret mqtt_password

# Custom Component Updater
custom_updater:
  show_installable: false
  hide_sensor: false
  track:
    - components
    - cards
    - python_scripts
  component_urls:
    - https://raw.githubusercontent.com/pnbruckner/homeassistant-config/master/custom_components.json
  card_urls:
    - https://raw.githubusercontent.com/kalkih/mini-media-player/master/tracker.json

# Binary Switch for Home and Away Automations
input_boolean:
  homeandawayauto:
    name: Home and Away Automations

google_assistant: !include google_assistant.yaml
light: !include lights.yaml
scene: !include scene.yaml
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
