homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret my_latitude
  longitude: !secret my_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret my_elevation
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: !secret my_timezone
  # Customization file
  customize: !include customize.yaml
  # Weather Forecast & Updates
  packages: !include_dir_named packages
  # LimitlessLED
  customize_domain:
    light:
      assumed_state: false

# Auth
  auth_providers:
    - type: homeassistant
  # Uncomment next line if you want to enable legacy API password support
    - type: legacy_api_password

# Python
# python_script:

# Map
map:

# Show Aussie Broadband CVC Capacity, BOM Satellite and Radar
camera:
  - platform: generic
    name: Aussie Broadband CVC Capacity
    still_image_url: !secret my_abb_cvc
  - platform: generic
    name: BOM Satellite
    still_image_url: !secret my_bom_sat
  - platform: generic
    name: !secret my_bom_radar_name_1
    still_image_url: !secret my_bom_1_radar
  - platform: generic
    name: !secret my_bom_radar_name_2
    still_image_url: !secret my_bom_2_radar 

# Show links to resources in log and frontend
# introduction:

# Enables the frontend
frontend:
  javascript_version: latest

# HTML5 Push Notifications
notify:
  - name: html5_notify
    platform: html5
    gcm_api_key: !secret gcm_api
    gcm_sender_id: !secret gcm_sender

# Enables configuration UI
config:

http:
  # Uncomment this to add a password (recommended!)
  api_password: !secret http_password
  # ssl_certificate: /ssl/fullchain.pem
  # ssl_key: /ssl/privkey.pem
  # trusted_networks:
  #   - !secret trusted_network
  ip_ban_enabled: True
  login_attempts_threshold: 5
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  # base_url: https://my-duck-dns-domain.duckdns.org:8123

# iFrame Configurator, Terminal, Tasmoadmin & MDI Icon Files
panel_iframe:
  configurator:
    title: Configurator
    icon: mdi:wrench
    url: !secret configurator
  ide:
    title: IDE
    icon: mdi:code-braces
    url: !secret ide-cloud9    
  terminal:
    title: Terminal
    icon: mdi:console
    url: !secret terminal
  tasmoadmin:
    title: Tasmo Admin
    icon: mdi:lightbulb-on
    url: !secret tasmoadmin
  logviewer:
    title: Log Viewer
    icon: mdi:script
    url: !secret logviewer
  mdiindex:
    title: MDI Icon Index
    icon: mdi:vector-square
    url: https://cdn.rawgit.com/james-fry/home-assistant-mdi/efd95d7a/home-assistant-mdi.html

# Recorder
recorder:
  purge_interval: 1
  purge_keep_days: 7

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:
  enable:
    - dlna_dmr

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Sensors
sensor:

# Certificate LetsEncrypt
  - platform: cert_expiry
    host: !secret my_letsencrypt
    port: !secret certificate_port
          
# CPU Resources Used & Temperature
  - platform: systemmonitor
    resources:
    - type: disk_use
      arg: /
    - type: disk_free
      arg: /
    - type: memory_use_percent
    - type: processor_use
    - type: last_boot
  - platform: command_line
    name: CPU Temperature
    command: "cat /sys/class/thermal/thermal_zone0/temp"
    unit_of_measurement: "°C"
    value_template: '{{ value | multiply(0.001) | round(1) }}'

# BOM
  - platform: bom
    station: !secret my_bom_station
    name: !secret my_bom_name
    monitored_conditions:
      - apparent_t
      - delta_t
      - gust_kmh
      - gust_kt
      - air_temp
      - dewpt
      - rain_trace
      - rel_hum
      - wind_dir
      - wind_spd_kmh
      - wind_spd_kt

# FritzBox
  - platform: fritzbox_netmonitor
    host: !secret my_fritz_host

# Speedtest
  - platform: speedtest
    minute:
      - 0
      - 30
    monitored_conditions:
      - ping
      - download
      - upload

# Speedtest Download Sensor Filter
  - platform: filter
    name: "Speedtest Download Filtered"
    entity_id: sensor.speedtest_download
    filters:
      - filter: lowpass
        time_constant: 20
        precision: 2
  - platform: filter
    name: "Speedtest Upload Filtered"
    entity_id: sensor.speedtest_upload
    filters:
      - filter: lowpass
        time_constant: 20
        precision: 2

# Sonarr
  - platform: sonarr
    api_key: !secret my_sonarr_api
    host: !secret my_sonarr_host
    port: !secret my_sonarr_port
    monitored_conditions:
      - series
      - upcoming
      - wanted
      - queue
      - commands
    days: 2

# Sonoff Firmware & Artisan Software Version
  - platform: command_line
    name: Sonoff Firmware Version Available
    command: /config/versionsonoffhtml.sh
    scan_interval: 21600
  - platform: command_line
    name: Artisan Software Version
    command: /config/versionartisanhtml.sh
    scan_interval: 21600
  - platform: mqtt
    name: "Toothbrush Firmware"
    state_topic: "stat/sonoff2/STATUS2"
    value_template: "v{{ value_json.StatusFWR.Version }}"
binary_sensor:
  - platform: template
    sensors:
      sonoff_update_available:
        value_template: >-
          {{ states.sensor.sonoff_firmware_version_available.state != states.sensor.toothbrush_firmware.state
              }}

# SABnzbd
sabnzbd:
  api_key: !secret sabnzbd_api
  host: !secret my_sab_host
  sensors:
    - current_status
    - speed
    - queue_size
    - queue_remaining
    - disk_size
    - disk_free
    - queue_count
    - day_size
    - week_size
    - month_size
    - total_size

# Graph Speedtest Download Filtered and Unfiltered
history_graph:
  speedtest:
    name: Speedtest Graph
    entities:
      - sensor.speedtest_download
      - sensor.speedtest_download_filtered
      - sensor.speedtest_upload
      - sensor.speedtest_upload_filtered
    hours_to_show: 24
    refresh: 1800

# iOS Component
ios:

# Text to speech
tts:
  - platform: google

# IFTTT
ifttt:
  key: !secret ifttt_api

# Kodi & Samsung TV
media_player:
  - platform: kodi
    host: !secret my_kodi_host
  - platform: samsungtv
    host: !secret my_samsung_host
    name: Samsung TV

# Xiaomi & Sonoff Switches
switch:
  - platform: xiaomi_miio
    name: Home Assistant
    host: !secret homeassistant-ip
    token: !secret homeassistant-token
  - platform: xiaomi_miio
    name: VPN Router
    host: !secret vpnrouter-ip
    token: !secret vpnrouter-token
  - platform: mqtt
    name: "Toothbrush"
    command_topic: "cmnd/sonoff2/power"
    state_topic: "stat/sonoff2/POWER"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    retain: true

# Wemo Switch
wemo:

# MQTT
mqtt:
  broker: core-mosquitto
  username: !secret mqtt_user_name
  password: !secret mqtt_password

google_assistant: !include google_assistant.yaml
light: !include lights.yaml
scene: !include scene.yaml
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
