homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret my_latitude
  longitude: !secret my_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret my_elevation
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: !secret my_timezone
  # Whitelisted Directories
  # whitelist_external_dirs:
  #   - /config/abbusage
  # Customization file
  customize: !include customize.yaml
  customize_glob: !include customize_glob.yaml
  # Fuel Monitor, System Monitor, Sun, Moon, Transport, Weather, Updates, Fire Incidents, Recycling Night, Themes Packages
  packages: !include_dir_named packages
  # LimitlessLED
  customize_domain:
    light:
      assumed_state: false
  auth_mfa_modules:
    - type: notify
    - type: totp

  auth_providers:
    - type: trusted_networks
      trusted_networks:
        - 127.0.0.1
        - ::1
        - 10.90.11.0/24
        - fd00::/8
        - !secret my_ipv6_network
      trusted_users:
        127.0.0.1: !secret user_id
        "::1": !secret user_id
        10.90.11.0/24: !secret user_id
        "fd00::/8": !secret user_id
        !secret trusted_user: !secret user_id
      allow_bypass_login: true
    - type: homeassistant

# System Health
system_health:

# Lovelace
#lovelace:
#  mode: yaml

# Python
# python_script:

# Map
map:

# Person
person:

# Device Tracker
#device_tracker:
#  - platform: fritz
#    host: !secret my_fritz_host
#    consider_home: 180
#    new_device_defaults:
#      track_new_devices: false
#      hide_if_away: false
#  - platform: fritz
#    host: !secret my_fritz_repeater
#    consider_home: 180
#    new_device_defaults:
#      track_new_devices: false
#      hide_if_away: false
#googlehome:
#  devices:
#    - host: !secret gh_lounge
#    - host: !secret gh_bed
#    - host: !secret gh_office

# Show links to resources in log and frontend
# introduction:

# Enables the frontend
frontend:
  javascript_version: latest

# HTML5 Push Notifications
notify:
  - platform: html5
    name: html5_notify
    vapid_pub_key: !secret vapid_pub
    vapid_prv_key: !secret vapid_priv
    vapid_email: !secret vapid_email
  - platform: group
    name: David iOS Notify
    services:
      - service: mobile_app_davids_iphone
        data:
          data:
            push:
              sound:
                name: default
      - service: mobile_app_davids_ipad
        data:
          data:
            push:
              sound:
                name: default

# Enables configuration UI
config:

http:
  # ssl_certificate: /ssl/fullchain.pem
  # ssl_key: /ssl/privkey.pem
  use_x_forwarded_for: true
  trusted_proxies:
    - 127.0.0.1
    - ::1
  ip_ban_enabled: True
  login_attempts_threshold: 5
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  base_url: !secret base_http_url

# Logger
logger:
  default: warn
  logs:
#   TransportNSW.transportnsw: error
    custom_components.sensor.authenticated: debug
#   homeassistant.components.http.view: error

# iFrame Configurator, Terminal, Tasmoadmin & MDI Icon Files
panel_iframe:
  configurator:
    title: Configurator
    icon: mdi:wrench
    url: !secret configurator
  ide:
    title: IDE
    icon: mdi:code-braces
    url: !secret ide-cloud9    
  glances:
    title: Glances
    icon: mdi:speedometer
    url: !secret glances
  custom_components:
    title: Custom Component Store
    icon: mdi:package-variant
    url: !secret customcomponent
  jupyterlab:
    title: JupyterLab
    icon: mdi:flask
    url: !secret jupyterlab
  portainer:
    title: Portainer
    icon: mdi:docker
    url: !secret portainer
  terminal:
    title: Terminal
    icon: mdi:console
    url: !secret terminal
  tasmoadmin:
    title: Tasmo Admin
    icon: mdi:lightbulb-on
    url: !secret tasmoadmin
  logviewer:
    title: Log Viewer
    icon: mdi:script
    url: !secret logviewer
  mdiindex:
    title: MDI Icon Index
    icon: mdi:vector-square
#   url: https://cdn.rawgit.com/james-fry/home-assistant-mdi/efd95d7a/home-assistant-mdi.html
    url: https://dev.materialdesignicons.com/icons
  vscode:
    title: Visual Studio Code
    icon: mdi:visual-studio-code
    url: !secret vscode
    
# Recorder
recorder: !include recorder.yaml

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:
  ignore:
    - yeelight
  enable:
    - dlna_dmr
    
# Yeelights
yeelight:
  devices:
    10.90.11.47:
      name: Fan Light
    10.90.11.7:
      name: Meals Area Light

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:
  exclude:
    domains:
      - automation
      - binary_sensor
      - geo_location
    entities:
      - sensor.busmonitor1
      - sensor.busmonitor
      - sensor.trainmonitor1
      - sensor.trainmonitor2
      - sensor.centralgosford
      - sensor.gosfordcentral
      - sensor.karionggosford
      - sensor.gosfordkariong
      - sensor.systemuptime

# View all events in a logbook
logbook:

# Sensors
sensor:

# Authentication Sensor
  - platform: authenticated
    enable_notification: true

# Certificate LetsEncrypt
  - platform: cert_expiry
    host: !secret my_letsencrypt
    port: !secret certificate_port

# Alarm Emails
  - platform: imap
    name: Alarm Triggers
    server: imap.gmail.com
    port: 993
    username: !secret outlooksyncuser
    password: !secret outlooksyncpass
    folder: inbox
    search: !secret alarmnotification
          
# Sonarr
  - platform: sonarr
    api_key: !secret my_sonarr_api
    host: !secret my_sonarr_host
    port: !secret my_sonarr_port
    monitored_conditions:
      - series
      - upcoming
      - wanted
      - queue
      - commands
    days: 2
  - platform: radarr
    api_key: !secret my_radarr_api
    host: !secret my_radarr_host
    port: !secret my_radarr_port
    monitored_conditions:
      - movies
      - upcoming
      - commands
      - status
    days: 10
  - platform: sonarr_upcoming_media
    api_key: !secret my_sonarr_api
    host: !secret my_sonarr_host
    port: !secret my_sonarr_port
    days: 60
    ssl: false
    max: 10
  - platform: radarr_upcoming_media
    api_key: !secret my_radarr_api
    host: !secret my_radarr_host
    port: !secret my_radarr_port
    days: 120
    ssl: false
    theaters: true
    max: 10

# Artisan Software Version
# Getting Artisan version from JSON
  - platform: rest
    resource: https://api.github.com/repos/artisan-roaster-scope/artisan/releases/latest
    name: Artisan Software Version
    username: !secret githubuser
    password: !secret githubpass
    authentication: basic
    value_template: '{{ value_json.tag_name }}'
    headers:
      Accept: application/vnd.github.v3+json
      Content-Type: application/json
      User-Agent: Home Assistant REST sensor

# Tasmota Firmware
# Getting Firmware from JSON for Tasmota
  - platform: rest
    resource: https://api.github.com/repos/arendst/Sonoff-Tasmota/releases/latest
    name: Sonoff Firmware Version Available
    username: !secret githubuser
    password: !secret githubpass
    authentication: basic
    value_template: '{{ value_json.tag_name }}'
    headers:
      Accept: application/vnd.github.v3+json
      Content-Type: application/json
      User-Agent: Home Assistant REST sensor
  - platform: mqtt
    name: "Coffee Maker Firmware"
    state_topic: "sonoff1/stat/STATUS2"
    value_template: 'v{{ value_json.StatusFWR.Version | replace("(sonoff)", "") | replace("(release-sonoff)", "") }}'
  - platform: mqtt
    name: "Toothbrush Firmware"
    state_topic: "sonoff2/stat/STATUS2"
    value_template: 'v{{ value_json.StatusFWR.Version | replace("(sonoff)", "") | replace("(release-sonoff)", "") }}'
  - platform: mqtt
    name: "Garage Door Firmware"
    state_topic: "sonoff5/stat/STATUS2"
    value_template: 'v{{ value_json.StatusFWR.Version | replace("(sonoff)", "") | replace("(release-sonoff)", "") }}'
  - platform: mqtt
    name: "Alarm Firmware"
    state_topic: "sonoff6/stat/STATUS2"
    value_template: 'v{{ value_json.StatusFWR.Version | replace("(sonoff)", "") | replace("(release-sonoff)", "") }}'
binary_sensor:
  - platform: template
    sensors:
      sonoff_update_available:
        value_template: >-
          {{ (states.sensor.sonoff_firmware_version_available.state > states.sensor.toothbrush_firmware.state) or (states.sensor.sonoff_firmware_version_available.state > states.sensor.coffee_maker_firmware.state) or (states.sensor.sonoff_firmware_version_available.state > states.sensor.garage_door_firmware.state) or (states.sensor.sonoff_firmware_version_available.state > states.sensor.alarm_firmware.state)
              }}

# SABnzbd
sabnzbd:
  api_key: !secret my_sabnzbd_api
  host: !secret my_sab_host
  port: 8080
  ssl: false
  sensors:
    - current_status
    - speed
    - queue_size
    - queue_remaining
    - disk_size
    - disk_free
    - queue_count
    - day_size
    - week_size
    - month_size
    - total_size

# iOS & Mobile App Component
#ios:
mobile_app:

# Text to speech
tts:
  - platform: google

# IFTTT
ifttt:
  key: !secret ifttt_api

# Xiaomi Switches & Hadockermon
switch:
  - platform: xiaomi_miio
    name: Home Assistant
    host: !secret homeassistant-ip
    token: !secret homeassistant-token
  - platform: xiaomi_miio
    name: VPN Router
    host: !secret vpnrouter-ip
    token: !secret vpnrouter-token
  - platform: hadockermon
    host: !secret my_hadockermon_host
    port: !secret my_hadockermon_port

# Wemo Switch
wemo:
  static:
    - !secret wemo_ip

# Custom Component Updater
custom_updater:
  hide_sensor: false
  track:
    - components
    - cards
    - python_scripts
  component_urls:
    - https://raw.githubusercontent.com/pnbruckner/homeassistant-config/master/custom_components.json
  card_urls:
    - https://raw.githubusercontent.com/kalkih/mini-media-player/master/tracker.json
    - https://raw.githubusercontent.com/kalkih/mini-graph-card/master/tracker.json
    - https://raw.githubusercontent.com/iammexx/home-assistant-config/master/ui/darksky/version.json

# Binary Switch for Home and Away Automations, Alarm & Garage Door
input_boolean:
  homeandawayauto:
    name: Home and Away Automations
  alarmgaragedoor:
    name: Alarm arm/disarm and Garage door shut/open
  overtime:
    name: Overtime

# Clear Out Gmail Alarm Notifications & Clean Known Devices file, ABB usage
shell_command:
  removealarm: python /config/emptyinbox.py
  clean_knowndevices: /bin/bash /config/clean_knowndevices.sh
  abbusage: /bin/bash /config/abbusage/abbusage_ha.sh

# Home Assistant Podcasts on gpodder
gpodder:
  username: !secret gpodder_user
  password: !secret gpodder_password
  sensor:
    - device: homeassistant
      enabled: true
      name: gPodder

google_assistant: !include google_assistant.yaml
light: !include lights.yaml
scene: !include scene.yaml
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
