# Default Config
# https://github.com/home-assistant/home-assistant/blob/dev/homeassistant/components/default_config/manifest.json
# documentation: https://www.home-assistant.io/integrations/default_config
default_config:

homeassistant:

# Customization file
  customize: !include customize.yaml
# customize_glob: !include customize_glob.yaml

# Fuel Monitor, System Monitor, Sun, Moon, Transport, Weather, Updates, Fire Incidents, Recycling Night, Themes Packages
  packages: !include_dir_named packages

# LimitlessLED use slider switch
  customize_domain:
    light:
      assumed_state: false

# Auth & 2FA
  auth_mfa_modules:
    - type: notify
    - type: totp
  auth_providers:
    - type: trusted_networks
      trusted_networks:
        - 127.0.0.1
        - ::1
        - !secret my_ipv4_network
        - fd00::/8
        - !secret zerotier_network
        - !secret my_ipv6_network
      trusted_users:
        127.0.0.1: !secret user_id
        "::1": !secret user_id
        !secret trusted_ipv4: !secret user_id
        "fd00::/8": !secret user_id
        !secret trusted_ipv6: !secret user_id
        !secret zerotier_network: !secret user_id
      allow_bypass_login: true
    - type: homeassistant

# Lovelace
#lovelace:
#  mode: yaml

# Python
# python_script:

# Device Trackers - Fritz!Box & iPhone Detect
device_tracker:
  - platform: fritz
    host: !secret my_fritz_host
    consider_home: 180
    new_device_defaults:
      track_new_devices: false
      hide_if_away: false
  - platform: iphonedetect
    consider_home: 60
    hosts:
      hostname1: !secret david_iphone
      hostname2: !secret david_ipad
      hostname3: !secret liz_iphone

# Enables the frontend
frontend:
  themes: !include_dir_merge_named themes
  extra_module_url:
    - /local/ThemeOverride.js

# HTML5 Push Notifications
notify:
  - platform: html5
    name: html5_notify
    vapid_pub_key: !secret vapid_pub
    vapid_prv_key: !secret vapid_priv
    vapid_email: !secret vapid_email
  - platform: group
    name: David iOS Notify
    services:
      - service: mobile_app_davids_iphone
        data:
          data:
            push:
              sound:
                name: default
      - service: mobile_app_davids_ipad
        data:
          data:
            push:
              sound:
                name: default

http:
  # ssl_certificate: /ssl/fullchain.pem
  # ssl_key: /ssl/privkey.pem
  use_x_forwarded_for: true
  trusted_proxies:
    - 127.0.0.1
    - ::1
  ip_ban_enabled: true
  login_attempts_threshold: 5
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  base_url: !secret base_http_url

# Logger
logger:
  default: warn  #warn
  logs:
#   TransportNSW.transportnsw: error
    custom_components.sensor.authenticated: debug
#   custom_components.iphonedetect: debug
#   homeassistant.components.http.view: error
#   hacs: debug
#   homeassistant.components.here_travel_time: debug

# iFrame/Panel Custom 
panel_iframe:
  jupyterlab:
    title: JupyterLab
    icon: mdi:flask
    url: !secret jupyterlab
  portainer:
    title: Portainer
    icon: mdi:docker
    url: !secret portainer
  tasmoadmin:
    title: Tasmo Admin
    icon: mdi:lightbulb-on
    url: !secret tasmoadmin
  tasui:
    title: Tasui
    icon: mdi:car-esp
    url: !secret tasui
  mdiindex:
    title: MDI Icon Index
    icon: mdi:vector-square
#   url: https://cdn.rawgit.com/james-fry/home-assistant-mdi/efd95d7a/home-assistant-mdi.html
    url: https://dev.materialdesignicons.com/icons

# Recorder
recorder: !include recorder.yaml

# Discover some devices automatically
discovery:
  ignore:
    - yeelight
  enable:
    - dlna_dmr

# Wemo
wemo:
# discovery: false
  static:
    - !secret wemo_ip

# Yeelights
yeelight:
  devices:
    !secret yeelight_fan:
      name: Fan Light
    !secret yeelight_meals:
      name: Meals Area Light

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:
  exclude:
    domains:
      - automation
      - binary_sensor
      - geo_location
    entities:
      - sensor.busmonitor1
      - sensor.busmonitor
      - sensor.trainmonitor1
      - sensor.trainmonitor2
      - sensor.centralgosford
      - sensor.gosfordcentral
      - sensor.karionggosford
      - sensor.gosfordkariong
      - sensor.systemuptime

# Sensors
sensor:

# Authentication Sensor
  - platform: authenticated
    enable_notification: true
    provider: 'ipapi'

# HERE Travel Time
  - platform: here_travel_time
    api_key: !secret here_api_key
    name: Travel to Home
    origin_entity_id: person.david
    destination_entity_id : zone.home

# Alarm Emails
  - platform: imap
    name: Alarm Triggers
    server: imap.gmail.com
    port: 993
    username: !secret outlooksyncuser
    password: !secret outlooksyncpass
    folder: inbox
    search: !secret alarmnotification

# Sonarr, Radarr and Upcoming Media
  - platform: sonarr
    api_key: !secret my_sonarr_api
    host: !secret my_sonarr_host
    port: !secret my_sonarr_port
    monitored_conditions:
      - series
      - upcoming
      - wanted
      - queue
      - commands
    days: 2
  - platform: radarr
    api_key: !secret my_radarr_api
    host: !secret my_radarr_host
    port: !secret my_radarr_port
    monitored_conditions:
      - movies
      - upcoming
      - commands
      - status
    days: 10
  - platform: sonarr_upcoming_media
    api_key: !secret my_sonarr_api
    host: !secret my_sonarr_host
    port: !secret my_sonarr_port
    days: 60
    ssl: false
    max: 10
  - platform: radarr_upcoming_media
    api_key: !secret my_radarr_api
    host: !secret my_radarr_host
    port: !secret my_radarr_port
    days: 120
    ssl: false
    theaters: true
    max: 10

# Artisan Software Version
# Getting Artisan version from JSON
  - platform: rest
    resource: https://api.github.com/repos/artisan-roaster-scope/artisan/releases/latest
    name: Artisan Software Version
    value_template: '{{ value_json.tag_name }}'
    headers:
      Authorization: !secret github-access-token-token
      Accept: application/vnd.github.v3+json
      Content-Type: application/json
      User-Agent: Home Assistant REST sensor

# Artisan Charge
  - platform: mqtt
    name: "Artisan Events"
    state_topic: "artisan"
    icon: mdi:coffee
    value_template: "{{ value_json.state }}"

# Tasmota Firmware
# Getting Firmware from JSON for Tasmota
  - platform: rest
    resource: https://api.github.com/repos/arendst/Tasmota/releases/latest
    name: Tasmota Firmware Version Available
    value_template: '{{ value_json.tag_name }}'
    headers:
      Authorization: !secret github-access-token-token
      Accept: application/vnd.github.v3+json
      Content-Type: application/json
      User-Agent: Home Assistant REST sensor
  - platform: mqtt
    name: "Coffee Maker Firmware"
    state_topic: "sonoff1/stat/STATUS2"
    value_template: 'v{{ value_json.StatusFWR.Version | replace("(tasmota)", "") | replace("(release-tasmota)", "") }}'
  - platform: mqtt
    name: "Toothbrush Firmware"
    state_topic: "sonoff2/stat/STATUS2"
    value_template: 'v{{ value_json.StatusFWR.Version | replace("(tasmota)", "") | replace("(release-tasmota)", "") }}'
  - platform: mqtt
    name: "RovingSI Firmware"
    state_topic: "sonoff3/stat/STATUS2"
    value_template: 'v{{ value_json.StatusFWR.Version | replace("(tasmota)", "") | replace("(release-tasmota)", "") }}'
  - platform: mqtt
    name: "Garage Door Firmware"
    state_topic: "sonoff5/stat/STATUS2"
    value_template: 'v{{ value_json.StatusFWR.Version | replace("(tasmota)", "") | replace("(release-tasmota)", "") }}'
  - platform: mqtt
    name: "Alarm Firmware"
    state_topic: "sonoff6/stat/STATUS2"
    value_template: 'v{{ value_json.StatusFWR.Version | replace("(tasmota)", "") | replace("(release-tasmota)", "") }}'
  - platform: mqtt
    name: "Nodemcu Lounge Firmware"
    state_topic: "nodemcu_lounge/stat/STATUS2"
    value_template: 'v{{ value_json.StatusFWR.Version | replace("(tasmota)", "") | replace("(release-tasmota)", "") }}'
  - platform: mqtt
    name: "Nodemcu Bedroom Firmware"
    state_topic: "nodemcu_bedroom/stat/STATUS2"
    value_template: 'v{{ value_json.StatusFWR.Version | replace("(tasmota)", "") | replace("(release-tasmota)", "") }}'
binary_sensor:
  - platform: template
    sensors:
      tasmota_update_available:
        value_template: >-
          {{ (states('sensor.tasmota_firmware_version_available') > states('sensor.toothbrush_firmware')) or (states('sensor.tasmota_firmware_version_available') > states('sensor.coffee_maker_firmware')) or (states('sensor.tasmota_firmware_version_available') > states('sensor.garage_door_firmware')) or (states('sensor.tasmota_firmware_version_available') > states('sensor.alarm_firmware'))
              }}

# SABnzbd
sabnzbd:
  api_key: !secret my_sabnzbd_api
  host: !secret my_sab_host
  port: 8080
  ssl: false
  sensors:
    - current_status
    - speed
    - queue_size
    - queue_remaining
    - disk_size
    - disk_free
    - queue_count
    - day_size
    - week_size
    - month_size
    - total_size

# Text to speech
tts:
  - platform: google_translate

# IFTTT
ifttt:
  key: !secret ifttt_api

# Xiaomi Switches & Hadockermon
switch:
  - platform: xiaomi_miio
    name: Home Assistant
    host: !secret homeassistant-ip
    token: !secret homeassistant-token
  - platform: xiaomi_miio
    name: VPN Router
    host: !secret vpnrouter-ip
    token: !secret vpnrouter-token
  - platform: hadockermon
    host: !secret my_hadockermon_host
    port: !secret my_hadockermon_port

# Binary Switch for Home and Away Automations, Alarm & Garage Door, Overtime & Holiday
input_boolean:
  homeandawayauto:
    name: Home and Away Automations
  alarmgaragedoor:
    name: Alarm arm/disarm and Garage door shut/open
  overtime:
    name: Overtime
  holiday:
    name: Holiday
  retrigger:
    name: Retrigger Docker Containers Restart

# Clear Out Gmail Alarm Notifications & Clean Known Devices file, ABB usage, Component/Card Versions
shell_command:
  removealarm: python /config/emptyinbox.py
  clean_knowndevices: /bin/bash /config/clean_knowndevices.sh

# Home Assistant Podcasts on gpodder
gpodder:
  username: !secret gpodder_user
  password: !secret gpodder_password
  sensor:
    - enabled: true
      name: gPodder
      device: homeassistant

google_assistant: !include google_assistant.yaml
light: !include lights.yaml
scene: !include scenes.yaml
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
