# LimitlessLED
- platform: limitlessled
  bridges:
    - host: !secret limitlessledhost
      version: 6
      port: 5987
      groups:
      - number: 1
        type: rgbww
        name: Lounge
      - number: 2
        type: rgbww
        name: Dining
      - number: 3
        type: rgbww
        name: Office
      - number: 4
        type: rgbww
        name: Desk
# Office Light Group
- platform: group
  name: Office Light Group
  entities:
    - light.office
    - light.desk