- id: '1507434167220'
  alias: Coffee Maker On
  trigger:
  - platform: time
    at: '07:00:00'
  - platform: time
    at: '07:15:00'
  - platform: time
    at: '08:00:00'
  - platform: time
    at: '12:00:00'
  - platform: time
    at: '19:00:00'
  - platform: time
    at: '20:00:00'
  - entity_id: person.liz
    from: 'not_home'
    platform: state
    to: 'home'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: 'input_boolean.homeandawayauto'
        state: 'on'
      - condition: or
        conditions:
          - condition: template
            value_template: "{{ now().strftime('%H:%M') == '07:00' and now().weekday()
              < 5  and (states('input_boolean.holiday') == 'off') }}"
          - condition: template
            value_template: "{{ now().strftime('%H:%M') == '07:15' and ((as_timestamp(now())
              - as_timestamp('2017-09-24 00:00:00')) / 86400)|int % 28 == 0 }}"
          - condition: template
            value_template: "{{ now().strftime('%H:%M') == '08:00' }}"
          - condition: template
            value_template: "{{ now().strftime('%H:%M') == '12:00' and ((as_timestamp(now())
              - as_timestamp('2017-09-24 00:00:00')) / 86400)|int % 28 == 0 }}"
          - condition: template
            value_template: "{{ now().strftime('%H:%M') == '19:00' and (states('input_boolean.overtime') == 'off') }}"
          - condition: template
            value_template: "{{ now().strftime('%H:%M') == '19:00' and now().weekday() > 4 }}"
          - condition: template
            value_template: "{{ now().strftime('%H:%M') == '20:00' and (states('input_boolean.overtime') == 'on') and now().weekday() < 5 }}"
          - condition: and
            conditions:
              - condition: template
                value_template: "{{ now().weekday() < 5 }}"
              - condition: time
                after: '18:00:00'
                before: '19:00:00'
              - condition: state
                entity_id: person.liz
                state: 'home'
  action:
  - service: switch.turn_on
    data:
      entity_id: switch.sonoff12914
  - condition: and
    conditions:
      - condition: template
        value_template: "{{ now().weekday() < 5 }}"
      - condition: time
        after: '18:00:00'
        before: '19:00:00'
      - condition: state
        entity_id: person.liz
        state: 'home'      
  - service: notify.david_ios_notify
    data:
      message: 'Coffee Maker On'
      title: 'Liz is home'
- id: '1507434167221'
  alias: Coffee Maker Off
  trigger:
  - platform: time
    at: '08:30:00'
  - platform: time
    at: '14:00:00'
  - platform: time
    at: '16:00:00'
  - platform: time
    at: '22:00:00'
  condition:
    condition: or
    conditions:
    - condition: template
      value_template: "{{ now().strftime('%H:%M') == '08:30' and ((as_timestamp(now())
        - as_timestamp('2017-09-24 00:00:00')) / 86400)|int % 28 == 0 }}"
    - condition: template
      value_template: "{{ now().strftime('%H:%M') == '14:00' and now().weekday()
        < 5  and (states('input_boolean.holiday') == 'off') }}"
    - condition: template
      value_template: "{{ now().strftime('%H:%M') == '16:00' }}"
    - condition: template
      value_template: "{{ now().strftime('%H:%M') == '22:00' }}"
  action:
  - service: switch.turn_off
    data:
      entity_id: switch.sonoff12914
