title: Home
resources:
  - url: /local/tracker-card.js?v=0.1.5
    type: js
  - url: /local/custom-lovelace/upcoming-media-card/upcoming-media-card.js?v=0.1.9
    type: js
  - url: /local/custom_ui/dark-sky-weather-card.js?v=1
    type: js
  - url: /local/mini-media-player.js?ver=0.8.2
    type: module
views:
  - title: Home Assistant
    icon: mdi:home-assistant
    cards:
      - type: vertical-stack
        cards:
          - type: entities
            title: System Information
            entities:
              - sensor.ssl_certificate_expiry
              - sensor.coffee_maker_firmware
              - sensor.toothbrush_firmware
              - sensor.sonoff_firmware_version_available
              - binary_sensor.sonoff_update_available
              - sensor.artisan_software_version
          - type: entities
            title: NUC Resources
            entities:
              - sensor.cpu_temperature
              - sensor.disk_use_
              - sensor.disk_free_
              - sensor.memory_use_percent
              - sensor.processor_use
              - sensor.last_boot
          - type: entities
            title: iOS Devices
            entities:
              - device_tracker.davids_iphone
              - sensor.davidsiphone_battery_level
              - sensor.davidsiphone_battery_state
              - device_tracker.davids_ipad
              - sensor.davidsipad_battery_level
              - sensor.davidsipad_battery_state
      - type: vertical-stack
        cards:
          - type: entities
            title: Updates
            entities:
              - sensor.hass_installed_version
              - sensor.hass_current_stable_version
              - sensor.hass_current_beta_version
              - sensor.hass_current_dev_version
              - sensor.hass_current_supervisor_version
              - binary_sensor.hass_update_available
          - type: custom:tracker-card
            title: Custom Card Updates
            trackers:
              - sensor.custom_card_tracker
              - sensor.custom_component_tracker
      - type: vertical-stack
        cards:
          - type: entities
            title: Internet
            entities:
              - sensor.speedtest_download
              - sensor.speedtest_download_filtered
              - sensor.speedtest_upload
              - sensor.speedtest_upload_filtered
              - sensor.speedtest_ping
              - sensor.fritz_netmonitor
          - type: history-graph
            title: Speedtest Download Graph
            hours_to_show: 24
            refresh_interval: 1800
            entities:
              - sensor.speedtest_download
              - sensor.speedtest_download_filtered
          - type: history-graph
            title: Speedtest Upload Graph
            hours_to_show: 24
            refresh_interval: 1800
            entities:
              - sensor.speedtest_upload
              - sensor.speedtest_upload_filtered
          - type: picture-entity
            title: Aussie Broadband CVC Capacity
            entity: camera.aussie_broadband_cvc_capacity
            camera_image: camera.aussie_broadband_cvc_capacity
            show_info: true
            tap_action: dialog
  - title: Weather
    icon: mdi:weather-cloudy
    cards:
      - type: vertical-stack
        cards:
          - type: entities
            title: Season, Sun & Moon Phase
            entities:
              - sensor.seasonname
              - sun.sun
              - sensor.sunrisetoday
              - sensor.sunsettoday
              - sensor.nextsunrise
              - sensor.nextsunset
              - sensor.daylightyesterday
              - sensor.daylighttoday
              - sensor.daylighttomorrow
              - sensor.yrwthr
              - sensor.moonphases
          - type: history-graph
            title: Change in Day Length
            hours_to_show: 168
            refresh_interval: 1800
            entities:
              - sensor.daylengthchange
          - type: entities
            title: Forecast
            entities:
              - sensor.forecast_0
              - sensor.forecast_1
              - sensor.forecast_2
              - sensor.forecast_3
              - sensor.forecast_4
              - sensor.forecast_5
              - sensor.forecast_6
              - sensor.forecast_7
      - type: vertical-stack
        cards:
          - type: custom:dark-sky-weather-card
            entity_sun: sun.sun
            entity_daily_summary: sensor.dark_sky_daily_summary
            entity_current_conditions: sensor.dark_sky_icon  
            entity_humidity: sensor.dark_sky_humidity
            entity_pressure: sensor.dark_sky_pressure
            entity_temperature: sensor.dark_sky_temperature
            entity_visibility: sensor.dark_sky_visibility
            entity_wind_bearing: sensor.dark_sky_wind_bearing
            entity_wind_speed: sensor.dark_sky_wind_speed
            entity_forecast_high_temp_1: sensor.dark_sky_daytime_high_temperature_1
            entity_forecast_high_temp_2: sensor.dark_sky_daytime_high_temperature_2
            entity_forecast_high_temp_3: sensor.dark_sky_daytime_high_temperature_3
            entity_forecast_high_temp_4: sensor.dark_sky_daytime_high_temperature_4
            entity_forecast_high_temp_5: sensor.dark_sky_daytime_high_temperature_5
            entity_forecast_low_temp_1: sensor.dark_sky_overnight_low_temperature
            entity_forecast_low_temp_2: sensor.dark_sky_overnight_low_temperature_1
            entity_forecast_low_temp_3: sensor.dark_sky_overnight_low_temperature_2
            entity_forecast_low_temp_4: sensor.dark_sky_overnight_low_temperature_3
            entity_forecast_low_temp_5: sensor.dark_sky_overnight_low_temperature_4
            entity_forecast_icon_1: sensor.dark_sky_icon_1
            entity_forecast_icon_2: sensor.dark_sky_icon_2
            entity_forecast_icon_3: sensor.dark_sky_icon_3
            entity_forecast_icon_4: sensor.dark_sky_icon_4
            entity_forecast_icon_5: sensor.dark_sky_icon_5
          - type: entities
            title: Weather from BOM Australia
            entities:
              - sensor.forecast_0
              - sensor.bom_gosford_air_temp_c
              - sensor.bom_gosford_delta_temp_c
              - sensor.bom_gosford_dew_point_c
              - sensor.bom_gosford_feels_like_c
              - sensor.bom_gosford_rain_today
              - sensor.bom_gosford_relative_humidity
              - sensor.bom_gosford_wind_direction
              - sensor.bom_gosford_wind_gust_kmh
              - sensor.bom_gosford_wind_gust_kt
              - sensor.bom_gosford_wind_speed_kmh
              - sensor.bom_gosford_wind_speed_kt
          - type: entities
            title: Dark Sky
            entities:
              - sensor.dark_sky_cloud_coverage
              - sensor.dark_sky_cloud_coverage_1
              - sensor.dark_sky_daily_summary
              - sensor.dark_sky_hourly_summary
              - sensor.dark_sky_summary
              - sensor.dark_sky_wind_speed
              - sensor.dark_sky_wind_speed_1
      - type: vertical-stack
        cards:
          - type: picture-entity
            title: BOM Satellite
            entity: camera.bom_satellite
            camera_image: camera.bom_satellite
            show_info: true
            tap_action: dialog
          - type: picture-entity
            title: BOM Radar Sydney
            entity: camera.bom_radar_sydney
            camera_image: camera.bom_radar_sydney
            show_info: true
            tap_action: dialog
          - type: picture-entity
            title: BOM Radar Newcastle
            entity: camera.bom_radar_newcastle
            camera_image: camera.bom_radar_newcastle
            show_info: true
            tap_action: dialog
  - title: Lights & Switches
    icon: mdi:power
    cards:
      - type: vertical-stack
        cards:
          - type: entities
            title: Light
            show_header_toggle: false
            entities:
              - light.dining
              - light.lounge
              - light.yeelight_white_34ce00887db6
              - light.yeelight_white_34ce00882e27
              - light.office_light_group
              - light.office
              - light.desk
          - type: entities
            title: Switch
            show_header_toggle: false
            entities:
              - switch.coffee_maker
              - switch.home_assistant
              - switch.hifi
              - switch.vpn_router
              - switch.toothbrush
      - type: vertical-stack
        cards:      
          - type: entities
            title: Automations
            entities:
              - automation.lights_on_failsafe
              - automation.lights_off_failsafe
              - automation.power_state_sonoff_on_ha_startup
              - automation.coffee_maker_on
              - automation.coffee_maker_off
              - automation.make_snapshot__copy_backups_to_dropbox
              - automation.sonoff_firmware_installed
              - automation.toothbrush_on
              - automation.toothbrush_off
              - automation.turn_lounge_light_on_elevation__25__after_4pm
              - automation.update_available
          - type: entities
            title: Holiday Automations
            entities:
              - automation.coffee_maker_on
              - automation.toothbrush_on
              - automation.turn_lounge_light_on_elevation__25__after_4pm
      - type: entities
        title: Scenes
        entities:
          - scene.bedtime
          - scene.dining_daylight
          - scene.dining_normal
          - scene.dining_warm
          - scene.lounge_100
          - scene.lounge_daylight
          - scene.lounge_movie
          - scene.lounge_normal
          - scene.lounge_warm
          - scene.office_all
          - scene.office_daylight
          - scene.office_main
          - scene.office_warm
          - scene.desk_daylight
          - scene.desk_normal
          - scene.desk_warm
  - title: Media
    icon: mdi:vlc
    cards:
      - type: media-control
        entity: media_player.all_speakers
      - type: media-control
        entity: media_player.living_areas
      - type: media-control
        entity: media_player.bedroom_speaker
      - type: media-control
        entity: media_player.office_speaker
      - type: media-control
        entity: media_player.lounge_speaker
      - type: media-control
        entity: media_player.lounge_room_tv
      - type: media-control
        entity: media_player.roku_5x46aj056306
      - type: media-control
        entity: media_player.foxtel_7587
      - type: media-control
        entity: media_player.kodi
      - type: media-control
        entity: media_player.osmc_vero4
      - type: media-control
        entity: media_player.txnr1009
      - type: media-control
        entity: media_player.samsung_tv
  - title: Media Mini
    icon: mdi:boombox
    cards:
      - type: entities
        title: Google Devices
        entities:
        - entity: media_player.all_speakers
          type: "custom:mini-media-player"
          group: true
          show_tts: google
          artwork: cover
          power_color: true
          scroll_info: true
        - entity: media_player.living_areas
          type: "custom:mini-media-player"
          group: true
          show_tts: google
          artwork: cover
          power_color: true
          scroll_info: true
        - entity: media_player.bedroom_speaker
          type: "custom:mini-media-player"
          group: true
          show_tts: google
          artwork: cover
          power_color: true
          scroll_info: true
        - entity: media_player.office_speaker
          type: "custom:mini-media-player"
          group: true
          show_tts: google
          artwork: cover
          power_color: true
          scroll_info: true
        - entity: media_player.lounge_speaker
          type: "custom:mini-media-player"
          group: true
          show_tts: google
          artwork: cover
          power_color: true
          scroll_info: true
        - entity: media_player.lounge_room_tv
          type: "custom:mini-media-player"
          group: true
          artwork: cover
          power_color: true
      - type: entities
        title: Other Media Players
        entities:
        - entity: media_player.roku_5x46aj056306
          type: "custom:mini-media-player"
          group: true
          artwork: cover
          power_color: true
          scroll_info: true
        - entity: media_player.foxtel_7587
          type: "custom:mini-media-player"
          group: true
          artwork: cover
          power_color: true
          scroll_info: true
        - entity: media_player.kodi
          type: "custom:mini-media-player"
          group: true
          artwork: cover
          power_color: true
          scroll_info: true
        - entity: media_player.osmc_vero4
          type: "custom:mini-media-player"
          group: true
          artwork: cover
          power_color: true
          scroll_info: true
        - entity: media_player.txnr1009
          type: "custom:mini-media-player"
          group: true
          artwork: cover
          power_color: true
          scroll_info: true
          show_source: true
        - entity: media_player.samsung_tv
          type: "custom:mini-media-player"
          group: true
          artwork: cover
          power_color: true
          show_source: true
  - title: TV & Movies
    icon: mdi:kodi
    panel: true
    cards:
      - type: horizontal-stack
        cards:
          - type: custom:upcoming-media-card
            service: sonarr
            title: Sonarr Upcoming
            image_style: poster
            clock: 12
            date: 'ddmm'
            max: 10
            show_color: '#ffffff'
            episode_color: '#000000'
            time_color: '#f41103'
            downloaded_color: '#000000'
            ribbon_color: '#03a9f4'
            border_color: 'grey'
            text_shadows: 'off'
            box_shadows: 'on'
          - type: custom:upcoming-media-card
            service: radarr
            title: Radarr Upcoming
            image_style: poster
            clock: 12
            date: 'ddmm'
            max: 10
            show_color: '#ffffff'
            episode_color: '#000000'
            time_color: '#f41103'
            downloaded_color: '#000000'
            ribbon_color: '#03a9f4'
            border_color: 'grey'
            text_shadows: 'off'
            box_shadows: 'on'
          - type: entities
            title: Newsgroups
            entities:
              - sensor.sabnzbd_status
              - sensor.sabnzbd_queue
              - sensor.sabnzbd_queue_count
              - sensor.sabnzbd_speed
              - sensor.sabnzbd_left
              - sensor.sabnzbd_disk
              - sensor.sabnzbd_disk_free
              - sensor.sabnzbd_daily_total
              - sensor.sabnzbd_weekly_total
              - sensor.sabnzbd_monthly_total
              - sensor.sabnzbd_total
              - sensor.sonarr_series
              - sensor.sonarr_upcoming
              - sensor.sonarr_wanted
              - sensor.sonarr_queue
              - sensor.sonarr_commands
  - title: Buses, Trains & Fuel
    icon: mdi:train
    cards:
      - type: vertical-stack
        cards:
          - type: entities
            title: Transport
            entities:
              - sensor.busmonitor1
              - sensor.busmonitor2
              - sensor.trainmonitor1
              - sensor.trainmonitor2
          - type: entities
            title: NSW Fuel Watch - Sydney
            entities:
              - sensor.caltex_woolworths_waitara_pdl
              - sensor.caltex_woolworths_turramurra_pdl
              - sensor.caltex_st_ives_pdl
              - sensor.caltex_st_ives_north_pdl
              - sensor.caltex_woolworths_glenrose_pdl
              - sensor.caltex_belrose_pdl
      - type: entities
        title: NSW Fuel Watch - Central Coast
        entities:
          - sensor.caltex_kariong_pdl
          - sensor.caltex_woolworths_pdl
          - sensor.caltex_gosford_west_pdl
          - sensor.caltex_gosford_west_pdl_2
          - sensor.caltex_gosford_west_pdl_3
          - sensor.caltex_woolworths_erina_pdl
          - sensor.caltex_wyoming_pdl
          - sensor.caltex_woolworths_tuggerah_pdl
          - sensor.caltex_woolworths_tuggerah_north_pdl
          - sensor.caltex_wyong_pdl
          - sensor.caltex_wyong_pdl_2
          - sensor.coles_express_kariong_dl
