# NSW Fuel Watch Search for /FuelCheckApp/v1/fuel/prices/bylocation
# Site: https://www.fuelcheck.nsw.gov.au/App/

sensor:
  - platform: nsw_fuel_station
    station_id: 17249
#   friendly_name: Caltex Woolies 155 The Entrance Rd Erina
#   sensor.caltex_woolworths_erina_pdl
    fuel_types:
      - PDL
  - platform: nsw_fuel_station
    station_id: 17310
#   friendly_name: Caltex 363 Mona Vale Rd St Ives North
#   sensor.caltex_st_ives_north_pdl
    fuel_types:
      - PDL
  - platform: nsw_fuel_station
    station_id: 17340
#   friendly_name: Caltex Langford Drive Kariong
#   sensor.caltex_kariong_pdl
    fuel_types:
      - PDL
  - platform: nsw_fuel_station
    station_id: 18253
#   friendly_name: Caltex 164 Mona Vale Rd St Ives Foodary
#   sensor.caltex_st_ives_foodary_pdl
    fuel_types:
      - PDL
  - platform: nsw_fuel_station
    station_id: 18323
#   friendly_name: Caltex 283 Manns Rd West Gosford
#   sensor.caltex_gosford_west_pdl_3
    fuel_types:
      - PDL
  - platform: nsw_fuel_station
    station_id: 2263
#   friendly_name: Caltex 465 Pacific Hwy Wyoming
#   sensor.caltex_wyoming_pdl
    fuel_types:
      - PDL
  - platform: nsw_fuel_station
    station_id: 2436
#   friendly_name: Caltex Woolies 59-61 Pacific Hwy Waitara
#   sensor.caltex_woolworths_waitara_pdl
    fuel_types:
      - PDL
  - platform: nsw_fuel_station
    station_id: 523
#   friendly_name: Caltex Woolies 186 Pacific Hwy Tuggerah
#   sensor.caltex_woolworths_tuggerah_north_pdl
    fuel_types:
      - PDL
  - platform: nsw_fuel_station
    station_id: 620
#   friendly_name: Caltex Woolies Westfield 24-26 Gavenlock Road
#   sensor.caltex_woolworths_tuggerah_pdl
    fuel_types:
      - PDL
  - platform: nsw_fuel_station
    station_id: 622
#   friendly_name: Caltex Woolies 522 Pacific Hwy Wyoming
#   sensor.caltex_woolworths_gosford_pdl
    fuel_types:
      - PDL
  - platform: nsw_fuel_station
    station_id: 643
#   friendly_name: Caltex Woolies 60 Glenn St Belrose
#   sensor.caltex_woolworths_glenrose_pdl
    fuel_types:
      - PDL
  - platform: nsw_fuel_station
    station_id: 663
#   friendly_name: Caltex Woolies 1233 Pacific Hwy Turramurra
#   sensor.caltex_woolworths_turramurra_pdl
    fuel_types:
      - PDL
  - platform: nsw_fuel_station
    station_id: 721
#   friendly_name: Caltex 153 Forest Way Belrose
#   sensor.caltex_belrose_pdl
    fuel_types:
      - PDL
  - platform: nsw_fuel_station
    station_id: 874
#   friendly_name: Caltex 30A Pacific Hwy West Gosford (From Gosford)
#   sensor.caltex_gosford_west_pdl_2
    fuel_types:
      - PDL
  - platform: nsw_fuel_station
    station_id: 819
#   friendly_name: Caltex 69-71 Pacific Hwy Gosford West (To Gosford)
#   sensor.caltex_gosford_west_pdl
    fuel_types:
      - PDL
  - platform: nsw_fuel_station
    station_id: 906
#   friendly_name: Caltex M1 Northbound
#   sensor.caltex_wyong_pdl
    fuel_types:
      - PDL
  - platform: nsw_fuel_station
    station_id: 907
#   friendly_name: Caltex M1 Southbound
#   sensor.caltex_wyong_pdl_2
    fuel_types:
      - PDL
  - platform: nsw_fuel_station
    station_id: 902
#   friendly_name: Shell 6-8 Pacific Hwy Kariong
#   sensor.coles_express_kariong_dl
    fuel_types:
      - DL

homeassistant:
  customize:
    package.node_anchors:
      common: &common
        package: "fuel"

    sensor.caltex_kariong_pdl:
      icon: mdi:gas-station
      <<: *common
    sensor.caltex_woolworths_gosford_pdl:
      icon: mdi:gas-station
      <<: *common
    sensor.caltex_gosford_west_pdl:
      icon: mdi:gas-station
      <<: *common
    sensor.caltex_gosford_west_pdl_2:
      icon: mdi:gas-station
      <<: *common
    sensor.caltex_gosford_west_pdl_3:
      icon: mdi:gas-station
      <<: *common
    sensor.caltex_woolworths_erina_pdl:
      icon: mdi:gas-station
      <<: *common
    sensor.caltex_wyoming_pdl:
      icon: mdi:gas-station
      <<: *common
    sensor.caltex_woolworths_tuggerah_pdl:
      icon: mdi:gas-station
      <<: *common
    sensor.caltex_woolworths_tuggerah_north_pdl:
      icon: mdi:gas-station
      <<: *common
    sensor.caltex_wyong_pdl:
      icon: mdi:gas-station
      <<: *common
    sensor.caltex_wyong_pdl_2:
      icon: mdi:gas-station
      <<: *common
    sensor.coles_express_kariong_dl:
      icon: mdi:gas-station
      <<: *common
    sensor.caltex_woolworths_waitara_pdl:
      icon: mdi:gas-station
      <<: *common
    sensor.caltex_woolworths_turramurra_pdl:
      icon: mdi:gas-station
      <<: *common
    sensor.caltex_st_ives_north_pdl:
      icon: mdi:gas-station
      <<: *common
    sensor.caltex_st_ives_foodary_pdl:
      icon: mdi:gas-station
      <<: *common
    sensor.caltex_woolworths_glenrose_pdl:
      icon: mdi:gas-station
      <<: *common
    sensor.caltex_belrose_pdl:
      icon: mdi:gas-station
      <<: *common
