# NSW Fuel Watch Search for /FuelCheckApp/v1/fuel/prices/bylocation
# Site: https://www.fuelcheck.nsw.gov.au/App/

sensor:
  - platform: nsw_fuel_station
    station_id: 18424
#   friendly_name: Caltex 153 Forest Way Belrose
#   sensor.caltex_belrose_pdl
    fuel_types:
      - PDL
  - platform: nsw_fuel_station
    station_id: 18323
#   friendly_name: Caltex 283 Manns Rd West Gosford
#   sensor.caltex_gosford_west_pdl_3
    fuel_types:
      - PDL
  - platform: nsw_fuel_station
    station_id: 874
#   friendly_name: Caltex 30A Pacific Hwy West Gosford (From Gosford)
#   sensor.caltex_gosford_west_pdl_2
    fuel_types:
      - PDL
  - platform: nsw_fuel_station
    station_id: 819
#   friendly_name: Caltex 69-71 Pacific Hwy Gosford West (To Gosford)
#   sensor.caltex_gosford_west_pdl
    fuel_types:
      - PDL
  - platform: nsw_fuel_station
    station_id: 17340
#   friendly_name: Caltex Langford Drive Kariong
#   sensor.caltex_kariong_pdl
    fuel_types:
      - PDL
  - platform: nsw_fuel_station
    station_id: 18253
#   friendly_name: Caltex 164 Mona Vale Rd St Ives Foodary
#   sensor.caltex_st_ives_foodary_pdl
    fuel_types:
      - PDL
  - platform: nsw_fuel_station
    station_id: 17310
#   friendly_name: Caltex 363 Mona Vale Rd St Ives North
#   sensor.caltex_st_ives_north_pdl
    fuel_types:
      - PDL
  - platform: nsw_fuel_station
    station_id: 17249
#   friendly_name: Caltex Woolies 155 The Entrance Rd Erina
#   sensor.caltex_woolworths_erina_pdl
    fuel_types:
      - PDL
  - platform: nsw_fuel_station
    station_id: 643
#   friendly_name: Caltex Woolies 60 Glenn St Belrose
#   sensor.caltex_woolworths_glenrose_pdl
    fuel_types:
      - PDL
  - platform: nsw_fuel_station
    station_id: 622
#   friendly_name: Caltex Woolies 522 Pacific Hwy Wyoming
#   sensor.caltex_woolworths_gosford_pdl
    fuel_types:
      - PDL
  - platform: nsw_fuel_station
    station_id: 523
#   friendly_name: Caltex Woolies 186 Pacific Hwy Tuggerah
#   sensor.caltex_woolworths_tuggerah_north_pdl
    fuel_types:
      - PDL
  - platform: nsw_fuel_station
    station_id: 620
#   friendly_name: Caltex Woolies Westfield 24-26 Gavenlock Road
#   sensor.caltex_woolworths_tuggerah_pdl
    fuel_types:
      - PDL
  - platform: nsw_fuel_station
    station_id: 663
#   friendly_name: Caltex Woolies 1233 Pacific Hwy Turramurra
#   sensor.caltex_woolworths_turramurra_pdl
    fuel_types:
      - PDL
  - platform: nsw_fuel_station
    station_id: 2436
#   friendly_name: Caltex Woolies 59-61 Pacific Hwy Waitara
#   sensor.caltex_woolworths_waitara_pdl
    fuel_types:
      - PDL
  - platform: nsw_fuel_station
    station_id: 2263
#   friendly_name: Caltex 465 Pacific Hwy Wyoming
#   sensor.caltex_wyoming_pdl
    fuel_types:
      - PDL
  - platform: nsw_fuel_station
    station_id: 907
#   friendly_name: Caltex M1 Southbound
#   sensor.caltex_wyong_pdl_2
    fuel_types:
      - PDL
  - platform: nsw_fuel_station
    station_id: 906
#   friendly_name: Caltex M1 Northbound
#   sensor.caltex_wyong_pdl
    fuel_types:
      - PDL
  - platform: nsw_fuel_station
    station_id: 902
#   friendly_name: Shell 6-8 Pacific Hwy Kariong
#   sensor.coles_express_kariong_dl
    fuel_types:
      - DL

# Create Sensors with friendly names

  - platform: template
    sensors:

      cc17249:
        value_template: "{{states('sensor.caltex_woolworths_erina_pdl')}}"
        friendly_name: Caltex Woolies 155 The Entrance Rd Erina
        unit_of_measurement: ¢/L
      cc17340:
        value_template: "{{states('sensor.caltex_kariong_pdl')}}"
        friendly_name: Caltex Langford Drive Kariong
        unit_of_measurement: ¢/L
      cc2263:
        value_template: "{{states('sensor.caltex_wyoming_pdl')}}"
        friendly_name: Caltex 465 Pacific Hwy Wyoming
        unit_of_measurement: ¢/L
      cc523:
        value_template: "{{states('sensor.caltex_woolworths_tuggerah_north_pdl')}}"
        friendly_name: Caltex Woolies 186 Pacific Hwy Tuggerah
        unit_of_measurement: ¢/L
      cc620:
        value_template: "{{states('sensor.caltex_woolworths_tuggerah_pdl')}}"
        friendly_name: Caltex Woolies Westfield 24-26 Gavenlock Road
        unit_of_measurement: ¢/L
      cc622:
        value_template: "{{states('sensor.caltex_woolworths_gosford_pdl')}}"
        friendly_name: Caltex Woolies 522 Pacific Hwy Wyoming
        unit_of_measurement: ¢/L
      ccgw1:
        value_template: "{{states('sensor.caltex_gosford_west_pdl')}}"
        friendly_name_template: >
          {% if state_attr('sensor.caltex_gosford_west_pdl', 'station_id') == 18323 %}
            Caltex 283 Manns Rd West Gosford
          {% elif state_attr('sensor.caltex_gosford_west_pdl', 'station_id') == 874 %}
            Caltex 30A Pacific Hwy West Gosford (From Gosford)
          {% else %}
            Caltex 69-71 Pacific Hwy Gosford West (To Gosford)
          {% endif %}
        unit_of_measurement: ¢/L
      ccgw2:
        value_template: "{{states('sensor.caltex_gosford_west_pdl_2')}}"
        friendly_name_template: >
          {% if state_attr('sensor.caltex_gosford_west_pdl_2', 'station_id') == 18323 %}
            Caltex 283 Manns Rd West Gosford
          {% elif state_attr('sensor.caltex_gosford_west_pdl_2', 'station_id') == 874 %}
            Caltex 30A Pacific Hwy West Gosford (From Gosford)
          {% else %}
            Caltex 69-71 Pacific Hwy Gosford West (To Gosford)
          {% endif %}
        unit_of_measurement: ¢/L
      ccgw3:
        value_template: "{{states('sensor.caltex_gosford_west_pdl_3')}}"
        friendly_name_template: >
          {% if state_attr('sensor.caltex_gosford_west_pdl_3', 'station_id') == 18323 %}
            Caltex 283 Manns Rd West Gosford
          {% elif state_attr('sensor.caltex_gosford_west_pdl_3', 'station_id') == 874 %}
            Caltex 30A Pacific Hwy West Gosford (From Gosford)
          {% else %}
            Caltex 69-71 Pacific Hwy Gosford West (To Gosford)
          {% endif %}
        unit_of_measurement: ¢/L
      ccm11:
        value_template: "{{states('sensor.caltex_wyong_pdl')}}"
        friendly_name_template: >
          {% if state_attr('sensor.caltex_wyong_pdl', 'station_id') == 906 %}
            Caltex M1 Northbound
          {% else %}
            Caltex M1 Southbound
          {% endif %}
        unit_of_measurement: ¢/L
      ccm12:
        value_template: "{{states('sensor.caltex_wyong_pdl_2')}}"
        friendly_name_template: >
          {% if state_attr('sensor.caltex_wyong_pdl_2', 'station_id') == 906 %}
            Caltex M1 Northbound
          {% else %}
            Caltex M1 Southbound
          {% endif %}
        unit_of_measurement: ¢/L
      syd17310:
        value_template: "{{states('sensor.caltex_st_ives_north_pdl')}}"
        friendly_name: Caltex 363 Mona Vale Rd St Ives North
        unit_of_measurement: ¢/L
      syd18253:
        value_template: "{{states('sensor.caltex_st_ives_foodary_pdl')}}"
        friendly_name: Caltex 164 Mona Vale Rd St Ives Foodary
        unit_of_measurement: ¢/L
      syd2436:
        value_template: "{{states('sensor.caltex_woolworths_waitara_pdl')}}"
        friendly_name: Caltex Woolies 59-61 Pacific Hwy Waitara
        unit_of_measurement: ¢/L
      syd643:
        value_template: "{{states('sensor.caltex_woolworths_glenrose_pdl')}}"
        friendly_name: Caltex Woolies 60 Glenn St Belrose
        unit_of_measurement: ¢/L
      syd663:
        value_template: "{{states('sensor.caltex_woolworths_turramurra_pdl')}}"
        friendly_name: Caltex Woolies 1233 Pacific Hwy Turramurra
        unit_of_measurement: ¢/L
      syd18424:
        value_template: "{{states('sensor.caltex_belrose_pdl')}}"
        friendly_name: Caltex 153 Forest Way Belrose
        unit_of_measurement: ¢/L
      cc902:
        value_template: "{{states('sensor.coles_express_kariong_dl')}}"
        friendly_name: Shell 6-8 Pacific Hwy Kariong
        unit_of_measurement: ¢/L

homeassistant:
  customize:
    package.node_anchors:
      common: &common
        package: "fuel"

    sensor.caltex_kariong_pdl:
      icon: mdi:gas-station
      <<: *common
    sensor.caltex_woolworths_gosford_pdl:
      icon: mdi:gas-station
      <<: *common
    sensor.caltex_gosford_west_pdl:
      icon: mdi:gas-station
      <<: *common
    sensor.caltex_gosford_west_pdl_2:
      icon: mdi:gas-station
      <<: *common
    sensor.caltex_gosford_west_pdl_3:
      icon: mdi:gas-station
      <<: *common
    sensor.caltex_woolworths_erina_pdl:
      icon: mdi:gas-station
      <<: *common
    sensor.caltex_wyoming_pdl:
      icon: mdi:gas-station
      <<: *common
    sensor.caltex_woolworths_tuggerah_pdl:
      icon: mdi:gas-station
      <<: *common
    sensor.caltex_woolworths_tuggerah_north_pdl:
      icon: mdi:gas-station
      <<: *common
    sensor.caltex_wyong_pdl:
      icon: mdi:gas-station
      <<: *common
    sensor.caltex_wyong_pdl_2:
      icon: mdi:gas-station
      <<: *common
    sensor.coles_express_kariong_dl:
      icon: mdi:gas-station
      <<: *common
    sensor.caltex_woolworths_waitara_pdl:
      icon: mdi:gas-station
      <<: *common
    sensor.caltex_woolworths_turramurra_pdl:
      icon: mdi:gas-station
      <<: *common
    sensor.caltex_st_ives_north_pdl:
      icon: mdi:gas-station
      <<: *common
    sensor.caltex_st_ives_foodary_pdl:
      icon: mdi:gas-station
      <<: *common
    sensor.caltex_woolworths_glenrose_pdl:
      icon: mdi:gas-station
      <<: *common
    sensor.caltex_belrose_pdl:
      icon: mdi:gas-station
      <<: *common
    sensor.cc17249:
      icon: mdi:gas-station
      <<: *common
    sensor.syd17310:
      icon: mdi:gas-station
      <<: *common
    sensor.cc17340:
      icon: mdi:gas-station
      <<: *common
    sensor.syd18253:
      icon: mdi:gas-station
      <<: *common
    sensor.ccgw1:
      icon: mdi:gas-station
      <<: *common
    sensor.ccgw2:
      icon: mdi:gas-station
      <<: *common
    sensor.ccgw3:
      icon: mdi:gas-station
      <<: *common
    sensor.cc2263:
      icon: mdi:gas-station
      <<: *common
    sensor.syd2436:
      icon: mdi:gas-station
      <<: *common
    sensor.cc523:
      icon: mdi:gas-station
      <<: *common
    sensor.cc620:
      icon: mdi:gas-station
      <<: *common
    sensor.cc622:
      icon: mdi:gas-station
      <<: *common
    sensor.syd643:
      icon: mdi:gas-station
      <<: *common
    sensor.syd663:
      icon: mdi:gas-station
      <<: *common
    sensor.syd18424:
      icon: mdi:gas-station
      <<: *common
    sensor.ccm11:
      icon: mdi:gas-station
      <<: *common
    sensor.ccm12:
      icon: mdi:gas-station
      <<: *common
    sensor.cc902:
      icon: mdi:gas-station
      <<: *common
