sensor:
# Getting Lovelace Card versions from JSON
# Custom Components
  - platform: rest
    resource: https://raw.githubusercontent.com/pnbruckner/homeassistant-config/master/custom_components.json
    name: Sun 
    username: !secret githubuser
    password: !secret githubpass
    authentication: basic
    value_template: '{{ value_json.sun.version }}'
    headers:
      Accept: application/vnd.github.v3+json
      Content-Type: application/json
      User-Agent: Home Assistant REST sensor

# Custom Cards
  - platform: rest
    resource: https://raw.githubusercontent.com/iammexx/home-assistant-config/master/ui/darksky/version.json
    name: Darksky
    value_template: "{{ value_json['dark-sky-weather-card'].version }}"
