# OpenNEM (National Energy Market)
sensor:
  - platform: opennem
    region: nsw1
    monitored_conditions:
      - battery_charging
      - battery_discharging
      - biomass
      - coal_black
      - coal_brown
      - exports
      - demand
      - distillate
      - fossilfuel
      - renewables
      - gas_ccgt
      - gas_ocgt
      - gas_recip
      - gas_steam
      - generation
      - hydro
      - imports
      - price
      - pumps
      - solar_rooftop
      - solar_utility
      - temperature
      - wind
