# OpenNEM (National Energy Market)
sensor:
  - platform: template
    sensors:
      opennem_nsw1_coal_black:
        value_template: "{{ state_attr('sensor.opennem_nsw', 'coal_black') }}"
        unit_of_measurement: MW
      opennem_nsw1_distillate:
        value_template: "{{ state_attr('sensor.opennem_nsw', 'distillate') }}"
        unit_of_measurement: MW
      opennem_nsw1_gas_ccgt:
        value_template: "{{ state_attr('sensor.opennem_nsw', 'gas_ccgt') }}"
        unit_of_measurement: MW
      opennem_nsw1_hydro:
        value_template: "{{ state_attr('sensor.opennem_nsw', 'hydro') }}"
        unit_of_measurement: MW
      opennem_nsw1_pumps:
        value_template: "{{ state_attr('sensor.opennem_nsw', 'pumps') }}"
        unit_of_measurement: MW
      opennem_nsw1_solar_utility:
        value_template: "{{ state_attr('sensor.opennem_nsw', 'solar_utility') }}"
        unit_of_measurement: MW
      opennem_nsw1_solar_rooftop:
        value_template: "{{ state_attr('sensor.opennem_nsw', 'solar_rooftop') }}"
        unit_of_measurement: MW
      opennem_nsw1_wind:
        value_template: "{{ state_attr('sensor.opennem_nsw', 'wind') }}"
        unit_of_measurement: MW
      opennem_nsw1_exports:
        value_template: "{{ state_attr('sensor.opennem_nsw', 'exports') }}"
        unit_of_measurement: MW
      opennem_nsw1_imports:
        value_template: "{{ state_attr('sensor.opennem_nsw', 'imports') }}"
        unit_of_measurement: MW
      opennem_nsw1_price:
        value_template: "{{ state_attr('sensor.opennem_nsw', 'price') }}"
        unit_of_measurement: $/MWh
      opennem_nsw1_demand:
        value_template: "{{ state_attr('sensor.opennem_nsw', 'demand') }}"
        unit_of_measurement: MW
      opennem_nsw1_generation:
        value_template: "{{ state_attr('sensor.opennem_nsw', 'generation') }}"
        unit_of_measurement: MW
      opennem_nsw1_temperature:
        value_template: "{{ state_attr('sensor.opennem_nsw', 'temperature') }}"
        unit_of_measurement: °C
      opennem_nsw1_fossilfuel:
        value_template: "{{ state_attr('sensor.opennem_nsw', 'fossilfuel') }}"
        unit_of_measurement: MW
      opennem_nsw1_renewables:
        value_template: "{{ state_attr('sensor.opennem_nsw', 'renewables') }}"
        unit_of_measurement: MW
      opennem_nsw1_emissionsfactor:
        value_template: "{{ state_attr('sensor.opennem_nsw', 'emissions_factor') }}"
      opennem_nsw1_flow_qld:
        value_template: "{{ state_attr('sensor.opennem_nsw', 'flow_QLD') }}"
        unit_of_measurement: MW
      opennem_nsw1_flow_vic:
        value_template: "{{ state_attr('sensor.opennem_nsw', 'flow_VIC') }}"
        unit_of_measurement: MW
      opennem_nsw1_genvsdemand:
        value_template: "{{ state_attr('sensor.opennem_nsw', 'genvsdemand') }}"
        unit_of_measurement: MW

homeassistant:
  customize:
    package.node_anchors:
      common: &common
        package: "opennem"

    sensor.opennem_nsw1_coal_black:
      friendly_name: Black Coal
      icon: mdi:transmission-tower
      <<: *common
    sensor.opennem_nsw1_emissionsfactor:
      friendly_name: Emissions Factor
      icon: mdi:transmission-tower
      <<: *common
    sensor.opennem_nsw1_distillate:
      friendly_name: Distillate
      icon: mdi:transmission-tower
      <<: *common
    sensor.opennem_nsw1_gas_ccgt:
      friendly_name: Gas (Combined Cycle Power Plant)
      icon: mdi:transmission-tower
      <<: *common
    sensor.opennem_nsw1_hydro:
      friendly_name: Hydro
      icon: mdi:transmission-tower
      <<: *common
    sensor.opennem_nsw1_pumps:
      friendly_name: Pumps
      icon: mdi:transmission-tower
      <<: *common
    sensor.opennem_nsw1_solar_utility:
      friendly_name: Solar (Utility)
      icon: mdi:transmission-tower
      <<: *common
    sensor.opennem_nsw1_solar_rooftop:
      friendly_name: Solar (Rooftop)
      icon: mdi:transmission-tower
      <<: *common
    sensor.opennem_nsw1_wind:
      friendly_name: Wind
      icon: mdi:transmission-tower
      <<: *common
    sensor.opennem_nsw1_exports:
      friendly_name: Exported Power
      icon: mdi:transmission-tower
      <<: *common
    sensor.opennem_nsw1_imports:
      friendly_name: Imported Power
      icon: mdi:transmission-tower
      <<: *common
    sensor.opennem_nsw1_price:
      friendly_name: Spot Price
      icon: mdi:transmission-tower
      <<: *common
    sensor.opennem_nsw1_temperature:
      friendly_name: Temperature
      icon: mdi:transmission-tower
      <<: *common
    sensor.opennem_nsw1_demand:
      friendly_name: Electricity Demand
      icon: mdi:transmission-tower
      <<: *common
    sensor.opennem_nsw1_fossilfuel:
      friendly_name: Generation by Fossil Fuels
      icon: mdi:transmission-tower
      <<: *common
    sensor.opennem_nsw1_generation:
      friendly_name: Electricity Generation
      icon: mdi:transmission-tower
      <<: *common
    sensor.opennem_nsw1_renewables:
      friendly_name: Generation by Renewables
      icon: mdi:transmission-tower
      <<: *common
    sensor.opennem_nsw1_genvsdemand:
      friendly_name: Generation vs Demand
      icon: mdi:transmission-tower
      <<: *common
    sensor.opennem_nsw1_flow_qld:
      friendly_name: Flow between NSW-QLD
      icon: mdi:transmission-tower
      <<: *common
    sensor.opennem_nsw1_flow_vic:
      friendly_name: Flow between NSW-VIC
      icon: mdi:transmission-tower
      <<: *common
