# ABB CVC Capacity
camera:
  - platform: generic
    name: Aussie Broadband CVC Capacity
    still_image_url: !secret my_abb_cvc

# CPU Resources Used & Temperature, Fritz!Box, Speedtest

sensor:

# FritzBox
  - platform: fritzbox_netmonitor
    host: !secret my_fritz_host

# Up since
  - platform: template
    sensors:
      systemuptime:
        value_template: >-
          {% set time = (as_timestamp(now()) - as_timestamp(states.sensor.last_boot.state)) %}
          {% set minutes = ((time % 3600) / 60) | int %}
          {% set hours = ((time % 86400) / 3600) | int %}
          {% set days = (time / 86400) | int %}
          {%- if time < 60 -%}
            Less than a minute
          {%- else -%}
            {%- if days > 0 -%}
              {%- if days == 1 -%}
                1 day
              {%- else -%}
                {{ days }} days
              {%- endif -%}
            {%- endif -%}
            {%- if hours > 0 -%}
              {%- if days > 0 -%}
                {{ ', ' }}
              {%- endif -%}
              {%- if hours == 1 -%}
                1 hour
              {%- else -%}
                {{ hours }} hours
              {%- endif -%}
            {%- endif -%}
            {%- if minutes > 0 -%}
              {%- if days > 0 or hours > 0 -%}
                {{ ', ' }}
              {%- endif -%}
              {%- if minutes == 1 -%}
                1 minute
              {%- else -%}
                {{ minutes }} minutes
              {%- endif -%}
            {%- endif -%}
          {%- endif -%}

#   command: /config/uptimemeas.sh
#   scan_interval: 60

# Speedtest
  - platform: speedtest
    minute:
      - 0
      - 30
    monitored_conditions:
      - ping
      - download
      - upload

# Speedtest Sensor Filters
  - platform: filter
    name: "Speedtest Download Filtered"
    entity_id: sensor.speedtest_download
    filters:
      - filter: lowpass
        time_constant: 20
        precision: 2
  - platform: filter
    name: "Speedtest Upload Filtered"
    entity_id: sensor.speedtest_upload
    filters:
      - filter: lowpass
        time_constant: 20
        precision: 2

# NUC Resources
  - platform: filter
    name: "NUC Memory Used Filtered"
    entity_id: sensor.memory_use_percent
    filters:
      - filter: lowpass
        time_constant: 20
        precision: 2
  - platform: filter
    name: "NUC Processor Used Filtered"
    entity_id: sensor.processor_use
    filters:
      - filter: lowpass
        time_constant: 20
        precision: 2

  - platform: command_line
    name: "CPU Temperature"
    command: "cat /sys/class/thermal/thermal_zone0/temp"
    unit_of_measurement: "°C"
    value_template: '{{ value | multiply(0.001) | round(1) }}'
  - platform: command_line
    name: "WAN IP Address"
    command: "wget -q -O - http://icanhazip.com/ | tail"
  - platform: systemmonitor
    resources:
    - type: disk_use
      arg: /
    - type: disk_free
      arg: /
    - type: disk_use_percent
      arg: /
    - type: memory_use_percent
    - type: memory_use
    - type: memory_free
    - type: swap_use_percent
    - type: load_1m
    - type: load_5m
    - type: load_15m
    - type: processor_use
    - type: ipv4_address
      arg: 'eno1'
    - type: ipv6_address
      arg: 'eno1'
    - type: network_in
      arg: 'eno1'
    - type: network_out
      arg: 'eno1'
    - type: last_boot
  - platform: template
    sensors:
      load:
        friendly_name: "Load Averages"
        value_template: '{{states.sensor.load_1m.state|round(2)}}, {{states.sensor.load_5m.state|round(2)}}, {{states.sensor.load_15m.state|round(2)}} (1, 5, 15 min)'
  - platform: statistics
    entity_id: sensor.memory_use_percent
    name: memory
  - platform: statistics
    entity_id: sensor.processor_use
    name: processor

# Graph Speedtest Download Filtered and Unfiltered
history_graph:
  speedtest:
    name: Speedtest Graph
    entities:
      - sensor.speedtest_download
      - sensor.speedtest_download_filtered
      - sensor.speedtest_upload
      - sensor.speedtest_upload_filtered
    hours_to_show: 24
    refresh: 1800

group:
  nuc_resources:
    name: "NUC Resources"
    view: no
    icon: mdi:server
    entities:
      - sensor.cpu_temperature
      - sensor.wan_ip_address
      - sensor.disk_use
      - sensor.disk_free_
      - sensor.disk_use_percent
      - sensor.memory_use_percent
      - sensor.memory_use
      - sensor.memory_free
      - sensor.swap_use_percent
      - sensor.load
      - sensor.processor_use
      - sensor.ipv4_address
      - sensor.network_in_eno1
      - sensor.network_out_eno1
      - sensor.last_boot
      - sensor.systemuptime

automation:
  - alias: 'System Runtime'
    initial_state: 'on'
    trigger:
      platform: time
      minutes: '/1'
      seconds: 0
    action:
      - service: homeassistant.update_entity
        entity_id: sensor.systemuptime
