# ABB CVC Capacity
camera:
  - platform: generic
    name: Aussie Broadband CVC Capacity
    still_image_url: !secret my_abb_cvc

# CPU Resources Used & Temperature, Fritz!Box, Speedtest

# Speedtest
speedtestdotnet:
  scan_interval: '00:30:00'
  monitored_conditions:
    - ping
    - download
    - upload

# Graph Speedtest Download Filtered and Unfiltered
history_graph:
  speedtest:
    name: Speedtest Graph
    entities:
      - sensor.speedtest_download
      - sensor.speedtest_download_filtered
      - sensor.speedtest_upload
      - sensor.speedtest_upload_filtered
    hours_to_show: 24
    refresh: 1800

sensor:

# Speedtest Sensor Filters
  - platform: filter
    name: "Speedtest Download Filtered"
    entity_id: sensor.speedtest_download
    filters:
      - filter: lowpass
        time_constant: 20
        precision: 2
  - platform: filter
    name: "Speedtest Upload Filtered"
    entity_id: sensor.speedtest_upload
    filters:
      - filter: lowpass
        time_constant: 20
        precision: 2

# FritzBox
  - platform: fritzbox_netmonitor
    host: !secret my_fritz_host

# Docker Containers
  - platform: rest
    resource: http://10.90.11.100:8126/container/sabnzbd/stats
    name: Sabnzbd Memory
    scan_interval: 900
    value_template: '{{ (value_json.memory_stats.usage /1024/1024) |round(2) }}'
    unit_of_measurement: 'MB'
  - platform: rest
    resource: http://10.90.11.100:8126/container/sonarr/stats
    name: Sonarr Memory
    scan_interval: 900
    value_template: '{{ (value_json.memory_stats.usage /1024/1024) |round(2) }}'
    unit_of_measurement: 'MB'
  - platform: rest
    resource: http://10.90.11.100:8126/container/radarr/stats
    name: Radarr Memory
    scan_interval: 900
    value_template: '{{ (value_json.memory_stats.usage /1024/1024) |round(2) }}'
    unit_of_measurement: 'MB'

# Up since
  - platform: template
    sensors:
      systemuptime:
        value_template: >-
          {% set time = (as_timestamp(now()) - as_timestamp(states('sensor.last_boot'))) %}
          {% set minutes = ((time % 3600) / 60) | int %}
          {% set hours = ((time % 86400) / 3600) | int %}
          {% set days = (time / 86400) | int %}
          {%- if time < 60 -%}
            Less than a minute
          {%- else -%}
            {%- if days > 0 -%}
              {%- if days == 1 -%}
                1 day
              {%- else -%}
                {{ days }} days
              {%- endif -%}
            {%- endif -%}
            {%- if hours > 0 -%}
              {%- if days > 0 -%}
                {{ ', ' }}
              {%- endif -%}
              {%- if hours == 1 -%}
                1 hour
              {%- else -%}
                {{ hours }} hours
              {%- endif -%}
            {%- endif -%}
            {%- if minutes > 0 -%}
              {%- if days > 0 or hours > 0 -%}
                {{ ', ' }}
              {%- endif -%}
              {%- if minutes == 1 -%}
                1 minute
              {%- else -%}
                {{ minutes }} minutes
              {%- endif -%}
            {%- endif -%}
          {%- endif -%}

# NUC Resources
  - platform: filter
    name: "NUC Memory Used Filtered"
    entity_id: sensor.memory_use_percent
    filters:
      - filter: lowpass
        time_constant: 20
        precision: 2
  - platform: filter
    name: "NUC Processor Used Filtered"
    entity_id: sensor.processor_use
    filters:
      - filter: lowpass
        time_constant: 20
        precision: 2
  - platform: command_line
    name: "CPU Temperature"
    command: "cat /sys/class/thermal/thermal_zone0/temp"
    unit_of_measurement: "°C"
    value_template: '{{ value | multiply(0.001) | round(1) }}'
  - platform: command_line
    name: "WAN IP Address"
    command: "wget -q -O - http://icanhazip.com/ | tail"
  - platform: systemmonitor
    resources:
    - type: disk_use
      arg: /
    - type: disk_free
      arg: /
    - type: disk_use_percent
      arg: /
    - type: memory_use_percent
    - type: memory_use
    - type: memory_free
    - type: swap_use_percent
    - type: load_1m
    - type: load_5m
    - type: load_15m
    - type: processor_use
    - type: ipv4_address
      arg: 'eno1'
    - type: ipv6_address
      arg: 'eno1'
    - type: network_in
      arg: 'eno1'
    - type: network_out
      arg: 'eno1'
    - type: last_boot
  - platform: template
    sensors:
      load:
        friendly_name: "Load Averages"
        value_template: "{{states('sensor.load_1m')|round(2)}}, {{states('sensor.load_5m')|round(2)}}, {{states('sensor.load_15m')|round(2)}} (1, 5, 15 min)"
  - platform: statistics
    entity_id: sensor.memory_use_percent
    name: memory
  - platform: statistics
    entity_id: sensor.processor_use
    name: processor

automation:
  - alias: 'System Runtime'
    trigger:
      platform: time_pattern
      minutes: '/1'
      seconds: 0
    action:
      - service: homeassistant.update_entity
        entity_id: sensor.systemuptime
  - alias: 'Update Speedtest'
    trigger:
      platform: homeassistant
      event: start
    action:
      - service: speedtestdotnet.speedtest

homeassistant:
  customize:

    sensor.disk_use:
      friendly_name: Disk Used
    sensor.disk_free:
      friendly_name: Disk Free
    sensor.disk_use_percent:
      friendly_name: Percent Disk Used
    sensor.memory_use_percent:
      friendly_name: Percent Memory Used
    sensor.memory_use:
      friendly_name: Memory Used
    sensor.memory_free:
      friendly_name: Memory Free
    sensor.swap_use_percent:
      friendly_name: Percent Swap Used
    sensor.load_1m:
      friendly_name: 1m Load
    sensor.load_5m:
      friendly_name: 5m Load
    sensor.load_15m:
      friendly_name: 15m Load
    sensor.load:
      friendly_name: Load Averages
      icon: mdi:memory
    sensor.processor_use:
      friendly_name: Processor Used
    sensor.ipv4_address:
      friendly_name: IPv4 Address
    sensor.wan_ip_address:
      friendly_name: WAN IP Address
      icon: mdi:server-network
    sensor.network_in_eno1:
      friendly_name: Network In
    sensor.network_out_eno1:
      friendly_name: Network Out
    sensor.last_boot:
      friendly_name: Last Boot
      device_class: timestamp
      icon: mdi:clock
    sensor.systemuptime:
      friendly_name: Since Last Boot
      icon: mdi:clock
    sensor.last_successful_authentication:
      friendly_name: Last Successful Authentication
      icon: mdi:shield-check
    sensor.memory_mean:
      friendly_name: Memory % Use Stats
      icon: mdi:memory
    sensor.processor_mean:
      friendly_name: Processor % Use Stats
      icon: mdi:memory
    sensor.artisan_software_version:
      icon: mdi:coffee
    sensor.fritz_netmonitor:
      friendly_name: Fritz Net Monitor
    sensor.hass_current_beta_version:
      icon: mdi:beta
    sensor.hass_current_dev_version:
      icon: mdi:alpha
    sensor.hass_installed_version:
      icon: mdi:approval
    sensor.cpu_temperature:
      icon: mdi:thermometer
    sensor.sonarr_memory:
      friendly_name: Sonarr Memory Used
      icon: mdi:television-classic
    sensor.radarr_memory:
      friendly_name: Radarr Memory Used
      icon: mdi:filmstrip
    sensor.sabnzbd_memory:
      friendly_name: Sabnzbd Memory Used
      icon: mdi:kodi
    sensor.sabnzbd_status:
      icon: mdi:download
    sensor.sabnzbd_queue:
      icon: mdi:download
    sensor.sabnzbd_queue_count:
      icon: mdi:download
    sensor.sabnzbd_speed:
      icon: mdi:speedometer
    sensor.sabnzbd_left:
      icon: mdi:download
    sensor.sabnzbd_disk:
      icon: mdi:harddisk
    sensor.sabnzbd_disk_free:
      icon: mdi:harddisk
    sensor.sabnzbd_daily_total:
      icon: mdi:disc
    sensor.sabnzbd_weekly_total:
      icon: mdi:disc
    sensor.sabnzbd_monthly_total:
      icon: mdi:disc
    sensor.sabnzbd_total:
      icon: mdi:disc
    sensor.speedtest_download_filtered:
      icon: mdi:speedometer
    sensor.speedtest_upload_filtered:
      icon: mdi:speedometer
