# Superloop CVC Capacity
#camera:
#  - platform: generic
#    name: Superloop CVC Capacity
#    still_image_url: !secret superloop_cvc

# Hadockermon
switch:
  - platform: rest
    resource: http://10.90.11.100:8126/container/sabnzbd
    name: HA Dockermon Sabnzbd
    body_on: '{"state": "start"}'
    body_off: '{"state": "stop"}'
    is_on_template: '{{ value_json is not none and value_json.state == "running" }}'
  - platform: rest
    resource: http://10.90.11.100:8126/container/sonarr
    name: HA Dockermon Sonarr
    body_on: '{"state": "start"}'
    body_off: '{"state": "stop"}'
    is_on_template: '{{ value_json is not none and value_json.state == "running" }}'
  - platform: rest
    resource: http://10.90.11.100:8126/container/radarr
    name: HA Dockermon Radarr
    body_on: '{"state": "start"}'
    body_off: '{"state": "stop"}'
    is_on_template: '{{ value_json is not none and value_json.state == "running" }}'
  - platform: rest
    resource: http://10.90.11.100:8126/container/lazylibrarian
    name: HA Dockermon Lazylibrarian
    body_on: '{"state": "start"}'
    body_off: '{"state": "stop"}'
    is_on_template: '{{ value_json is not none and value_json.state == "running" }}'
  - platform: rest
    resource: http://10.90.11.100:8126/container/portainer
    name: HA Dockermon Portainer
    body_on: '{"state": "start"}'
    body_off: '{"state": "stop"}'
    is_on_template: '{{ value_json is not none and value_json.state == "running" }}'

sensor:

# CPU Resources Used & Temperature, Fritz!Box
# Speedtest Sensor Filters
  - platform: filter
    name: "Speedtest Download Filtered"
    entity_id: sensor.speedtest_download
    filters:
      - filter: lowpass
        time_constant: 20
        precision: 2
  - platform: filter
    name: "Speedtest Upload Filtered"
    entity_id: sensor.speedtest_upload
    filters:
      - filter: lowpass
        time_constant: 20
        precision: 2

# FritzBox
  - platform: fritzbox_netmonitor
    host: !secret my_fritz_host

# Docker Containers
  - platform: rest
    resource: http://10.90.11.100:8126/container/ha_dockermon/stats
    name: HA Dockermon Memory
    scan_interval: 900
    value_template: '{{ (value_json.memory_stats.usage /1024/1024) |round(2) }}'
    unit_of_measurement: 'MB'
  - platform: average
    name: ha_dockermon_memory_average
    entities:
      - sensor.ha_dockermon_memory
    duration:
      days: 2
  - platform: rest
    resource: http://10.90.11.100:8126/container/lazylibrarian/stats
    name: LazyLibrarian Memory
    scan_interval: 900
    value_template: '{{ (value_json.memory_stats.usage /1024/1024) |round(2) }}'
    unit_of_measurement: 'MB'
  - platform: average
    name: lazylibrarian_memory_average
    entities:
      - sensor.lazylibrarian_memory
    duration:
      days: 2
  - platform: rest
    resource: http://10.90.11.100:8126/container/sabnzbd/stats
    name: Sabnzbd Memory
    scan_interval: 900
    value_template: '{{ (value_json.memory_stats.usage /1024/1024) |round(2) }}'
    unit_of_measurement: 'MB'
  - platform: average
    name: sabnzbd_memory_average
    entities:
      - sensor.sabnzbd_memory
    duration:
      days: 2
  - platform: rest
    resource: http://10.90.11.100:8126/container/sonarr/stats
    name: Sonarr Memory
    scan_interval: 900
    value_template: '{{ (value_json.memory_stats.usage /1024/1024) |round(2) }}'
    unit_of_measurement: 'MB'
  - platform: average
    name: sonarr_memory_average
    entities:
      - sensor.sonarr_memory
    duration:
      days: 2
  - platform: rest
    resource: http://10.90.11.100:8126/container/radarr/stats
    name: Radarr Memory
    scan_interval: 900
    value_template: '{{ (value_json.memory_stats.usage /1024/1024) |round(2) }}'
    unit_of_measurement: 'MB'
  - platform: average
    name: radarr_memory_average
    entities:
      - sensor.radarr_memory
    duration:
      days: 2
  - platform: rest
    resource: http://10.90.11.100:8126/container/addon_7be23ff5_dropbox_sync/stats
    name: Dropbox Sync Memory
    scan_interval: 900
    value_template: '{{ (value_json.memory_stats.usage /1024/1024) |round(2) }}'
    unit_of_measurement: 'MB'
  - platform: average
    name: dropbox_sync_memory_average
    entities:
      - sensor.dropbox_sync_memory
    duration:
      days: 2
  - platform: rest
    resource: http://10.90.11.100:8126/container/addon_a0d7b954_appdaemon/stats
    name: Appdaemon Memory
    scan_interval: 900
    value_template: '{{ (value_json.memory_stats.usage /1024/1024) |round(2) }}'
    unit_of_measurement: 'MB'
  - platform: average
    name: appdaemon_memory_average
    entities:
      - sensor.appdaemon_memory
    duration:
      days: 2
  - platform: rest
    resource: http://10.90.11.100:8126/container/addon_a0d7b954_glances/stats
    name: Glances Memory
    scan_interval: 900
    value_template: '{{ (value_json.memory_stats.usage /1024/1024) |round(2) }}'
    unit_of_measurement: 'MB'
  - platform: average
    name: glances_memory_average
    entities:
      - sensor.glances_memory
    duration:
      days: 2
  - platform: rest
    resource: http://10.90.11.100:8126/container/addon_a0d7b954_logviewer/stats
    name: Logviewer Memory
    scan_interval: 900
    value_template: '{{ (value_json.memory_stats.usage /1024/1024) |round(2) }}'
    unit_of_measurement: 'MB'
  - platform: average
    name: logviewer_memory_average
    entities:
      - sensor.logviewer_memory
    duration:
      days: 2
  - platform: rest
    resource: http://10.90.11.100:8126/container/addon_a0d7b954_sonweb/stats
    name: Tasmoadmin Memory
    scan_interval: 900
    value_template: '{{ (value_json.memory_stats.usage /1024/1024) |round(2) }}'
    unit_of_measurement: 'MB'
  - platform: average
    name: tasmoadmin_memory_average
    entities:
      - sensor.tasmoadmin_memory
    duration:
      days: 2
  - platform: rest
    resource: http://10.90.11.100:8126/container/addon_a0d7b954_ssh/stats
    name: SSH & Web Terminal Memory
    scan_interval: 900
    value_template: '{{ (value_json.memory_stats.usage /1024/1024) |round(2) }}'
    unit_of_measurement: 'MB'
  - platform: average
    name: ssh_memory_average
    entities:
      -  sensor.ssh_web_terminal_memory
    duration:
      days: 2
  - platform: rest
    resource: http://10.90.11.100:8126/container/addon_a0d7b954_vscode/stats
    name: VSCode Memory
    scan_interval: 900
    value_template: '{{ (value_json.memory_stats.usage /1024/1024) |round(2) }}'
    unit_of_measurement: 'MB'
  - platform: average
    name: vscode_memory_average
    entities:
      - sensor.vscode_memory
    duration:
      days: 2
  - platform: rest
    resource: http://10.90.11.100:8126/container/addon_a0d7b954_zerotier/stats
    name: ZeroTier One Memory
    scan_interval: 900
    value_template: '{{ (value_json.memory_stats.usage /1024/1024) |round(2) }}'
    unit_of_measurement: 'MB'
  - platform: average
    name: zerotier_one_memory_average
    entities:
      - sensor.zerotier_one_memory
    duration:
      days: 2
  - platform: rest
    resource: http://10.90.11.100:8126/container/addon_core_configurator/stats
    name: Configurator Memory
    scan_interval: 900
    value_template: '{{ (value_json.memory_stats.usage /1024/1024) |round(2) }}'
    unit_of_measurement: 'MB'
  - platform: average
    name: configurator_memory_average
    entities:
      - sensor.configurator_memory
    duration:
      days: 2
  - platform: rest
    resource: http://10.90.11.100:8126/container/addon_core_mariadb/stats
    name: MariaDB Memory
    scan_interval: 900
    value_template: '{{ (value_json.memory_stats.usage /1024/1024) |round(2) }}'
    unit_of_measurement: 'MB'
  - platform: average
    name: mariadb_memory_average
    entities:
      - sensor.mariadb_memory
    duration:
      days: 2
  - platform: rest
    resource: http://10.90.11.100:8126/container/addon_a0d7b954_phpmyadmin/stats
    name: phpMyAdmin Memory
    scan_interval: 900
    value_template: '{{ (value_json.memory_stats.usage /1024/1024) |round(2) }}'
    unit_of_measurement: 'MB'
  - platform: average
    name: phpmyadmin_memory_average
    entities:
      - sensor.phpmyadmin_memory
    duration:
      days: 2
  - platform: rest
    resource: http://10.90.11.100:8126/container/addon_core_mosquitto/stats
    name: Mosquitto Memory
    scan_interval: 900
    value_template: '{{ (value_json.memory_stats.usage /1024/1024) |round(2) }}'
    unit_of_measurement: 'MB'
  - platform: average
    name: mosquitto_memory_average
    entities:
      - sensor.mosquitto_memory
    duration:
      days: 2
  - platform: rest
    resource: http://10.90.11.100:8126/container/addon_core_samba/stats
    name: Samba Memory
    scan_interval: 900
    value_template: '{{ (value_json.memory_stats.usage /1024/1024) |round(2) }}'
    unit_of_measurement: 'MB'
  - platform: average
    name: samba_memory_average
    entities:
      - sensor.samba_memory
    duration:
      days: 2
  - platform: rest
    resource: http://10.90.11.100:8126/container/addon_2974f5cf_caddy2/stats
    name: Caddy Memory
    scan_interval: 900
    value_template: '{{ (value_json.memory_stats.usage /1024/1024) |round(2) }}'
    unit_of_measurement: 'MB'
  - platform: average
    name: caddy_memory_average
    entities:
      - sensor.caddy_memory
    duration:
      days: 2
  - platform: rest
    resource: http://10.90.11.100:8126/container/portainer/stats
    name: Portainer Memory
    scan_interval: 900
    value_template: '{{ (value_json.memory_stats.usage /1024/1024) |round(2) }}'
    unit_of_measurement: 'MB'
  - platform: average
    name: portainer_memory_average
    entities:
      - sensor.portainer_memory
    duration:
      days: 2

# Up since
  - platform: template
    sensors:
      systemuptime:
        value_template: >-
          {% set time = (as_timestamp(now()) - as_timestamp(states('sensor.last_boot'))) %}
          {% set minutes = ((time % 3600) / 60) | int %}
          {% set hours = ((time % 86400) / 3600) | int %}
          {% set days = (time / 86400) | int %}
          {%- if time < 60 -%}
            Less than a minute
          {%- else -%}
            {%- if days > 0 -%}
              {%- if days == 1 -%}
                1 day
              {%- else -%}
                {{ days }} days
              {%- endif -%}
            {%- endif -%}
            {%- if hours > 0 -%}
              {%- if days > 0 -%}
                {{ ', ' }}
              {%- endif -%}
              {%- if hours == 1 -%}
                1 hour
              {%- else -%}
                {{ hours }} hours
              {%- endif -%}
            {%- endif -%}
            {%- if minutes > 0 -%}
              {%- if days > 0 or hours > 0 -%}
                {{ ', ' }}
              {%- endif -%}
              {%- if minutes == 1 -%}
                1 minute
              {%- else -%}
                {{ minutes }} minutes
              {%- endif -%}
            {%- endif -%}
          {%- endif -%}

# NUC Resources
  - platform: filter
    name: "NUC Memory Used Filtered"
    entity_id: sensor.memory_use_percent
    filters:
      - filter: lowpass
        time_constant: 20
        precision: 2
  - platform: filter
    name: "NUC Processor Used Filtered"
    entity_id: sensor.processor_use
    filters:
      - filter: lowpass
        time_constant: 20
        precision: 2
  - platform: command_line
    name: "CPU Temperature"
    command: "cat /sys/class/thermal/thermal_zone0/temp"
    unit_of_measurement: "°C"
    value_template: '{{ value | multiply(0.001) | round(1) }}'
  - platform: command_line
    name: "WAN IP Address"
    command: "wget -q -O - http://icanhazip.com/ | tail"
  - platform: systemmonitor
    resources:
    - type: disk_use
      arg: /
    - type: disk_free
      arg: /
    - type: disk_use_percent
      arg: /
    - type: memory_use_percent
    - type: memory_use
    - type: memory_free
    - type: swap_use_percent
    - type: load_1m
    - type: load_5m
    - type: load_15m
    - type: processor_use
    - type: ipv4_address
      arg: 'eno1'
    - type: ipv6_address
      arg: 'eno1'
    - type: network_in
      arg: 'eno1'
    - type: network_out
      arg: 'eno1'
    - type: last_boot
  - platform: template
    sensors:
      load:
        friendly_name: "Load Averages"
        value_template: "{{states('sensor.load_1m')|round(2)}}, {{states('sensor.load_5m')|round(2)}}, {{states('sensor.load_15m')|round(2)}} (1, 5, 15 min)"
  - platform: statistics
    entity_id: sensor.memory_use_percent
    name: memory
  - platform: statistics
    entity_id: sensor.processor_use
    name: processor

automation:
  - alias: 'System Runtime'
    trigger:
      platform: time_pattern
      minutes: '/1'
      seconds: 0
    action:
      - service: homeassistant.update_entity
        entity_id: sensor.systemuptime
  - alias: 'Update Speedtest'
    trigger:
      platform: homeassistant
      event: start
    action:
      - service: speedtestdotnet.speedtest

homeassistant:
  customize:
    package.node_anchors:
      common: &common
        package: "sysmonitor"

    sensor.disk_use:
      friendly_name: Disk Used
      <<: *common
    sensor.disk_free:
      friendly_name: Disk Free
      <<: *common
    sensor.disk_use_percent:
      friendly_name: Percent Disk Used
      <<: *common
    sensor.memory_use_percent:
      friendly_name: Percent Memory Used
      <<: *common
    sensor.memory_use:
      friendly_name: Memory Used
      <<: *common
    sensor.memory_free:
      friendly_name: Memory Free
      <<: *common
    sensor.swap_use_percent:
      friendly_name: Percent Swap Used
      <<: *common
    sensor.load_1m:
      friendly_name: 1m Load
      <<: *common
    sensor.load_5m:
      friendly_name: 5m Load
      <<: *common
    sensor.load_15m:
      friendly_name: 15m Load
      <<: *common
    sensor.load:
      friendly_name: Load Averages
      icon: mdi:memory
      <<: *common
    sensor.processor_use:
      friendly_name: Processor Used
      <<: *common
    sensor.ipv4_address:
      friendly_name: IPv4 Address
      <<: *common
    sensor.wan_ip_address:
      friendly_name: WAN IP Address
      icon: mdi:server-network
      <<: *common
    sensor.network_in_eno1:
      friendly_name: Network In
      <<: *common
    sensor.network_out_eno1:
      friendly_name: Network Out
      <<: *common
    sensor.last_boot:
      friendly_name: Last Boot
      device_class: timestamp
      icon: mdi:clock
      <<: *common
    sensor.systemuptime:
      friendly_name: Since Last Boot
      icon: mdi:clock
      <<: *common
    sensor.last_successful_authentication:
      friendly_name: Last Successful Authentication
      icon: mdi:shield-check
      <<: *common
    sensor.memory:
      friendly_name: Memory % Use Stats
      icon: mdi:memory
      <<: *common
    sensor.processor:
      friendly_name: Processor % Use Stats
      icon: mdi:memory
      <<: *common
    sensor.artisan_software_version:
      icon: mdi:coffee
      <<: *common
    sensor.fritz_netmonitor:
      friendly_name: Fritz Net Monitor
      <<: *common
    sensor.hass_current_beta_version:
      icon: mdi:beta
      <<: *common
    sensor.hass_current_dev_version:
      icon: mdi:alpha
      <<: *common
    sensor.hass_installed_version:
      icon: mdi:approval
      <<: *common
    sensor.cpu_temperature:
      icon: mdi:thermometer
      <<: *common
    sensor.sonarr_memory:
      friendly_name: Sonarr Memory Used
      icon: mdi:television-classic
      <<: *common
    sensor.radarr_memory:
      friendly_name: Radarr Memory Used
      icon: mdi:filmstrip
      <<: *common
    sensor.sabnzbd_memory:
      friendly_name: Sabnzbd Memory Used
      icon: mdi:kodi
      <<: *common
    sensor.sabnzbd_status:
      icon: mdi:download
      <<: *common
    sensor.sabnzbd_queue:
      icon: mdi:download
      <<: *common
    sensor.sabnzbd_queue_count:
      icon: mdi:download
      <<: *common
    sensor.sabnzbd_speed:
      icon: mdi:speedometer
      <<: *common
    sensor.sabnzbd_left:
      icon: mdi:download
      <<: *common
    sensor.sabnzbd_disk:
      icon: mdi:harddisk
      <<: *common
    sensor.sabnzbd_disk_free:
      icon: mdi:harddisk
      <<: *common
    sensor.sabnzbd_daily_total:
      icon: mdi:disc
      <<: *common
    sensor.sabnzbd_weekly_total:
      icon: mdi:disc
      <<: *common
    sensor.sabnzbd_monthly_total:
      icon: mdi:disc
      <<: *common
    sensor.sabnzbd_total:
      icon: mdi:disc
      <<: *common
    sensor.speedtest_download_filtered:
      icon: mdi:speedometer
      <<: *common
    sensor.speedtest_upload_filtered:
      icon: mdi:speedometer
      <<: *common
