input_select:
  theme_switcher:
    name: 'Switch Theme'
    options:
     - 'default'
     - 'amoled'
     - 'AMOLED Blue'
     - 'aqua-fiesta'
     - 'another_dark'
     - 'blackened'
     - 'blue_night'
     - 'christmas'
     - 'clear'
     - 'clear-dark'
     - 'dark_mint'
     - 'dark-blue'
     - 'dark-blue-purple'
     - 'dark-cyan'
     - 'dark-gray'
     - 'dark-green'
     - 'darkish'
     - 'dark-light-red'
     - 'dark-orange'
     - 'dark_orange'
     - 'dark-purple'
     - 'dark-red'
     - 'dark-yellow'
     - 'dark_teal'
     - 'discord'
     - 'Google Dark Theme'
     - 'Google Light Theme'
     - 'gray-green'
     - 'Green Dark Mode'
     - 'Green light Mode'
     - 'green-slate'
     - 'green_slate'
     - 'grey_night'
     - 'halloween'
     - 'ios-light-mode'
     - 'ios-dark-mode'
     - 'light-blue'
     - 'light-cyan'
     - 'light-green'
     - 'light-navy-blue'
     - 'light-orange'
     - 'light-purple'
     - 'light-red'
     - 'light-yellow'
     - 'material_dark_green'
     - 'material_dark_pink'
     - 'material_dark_red'
     - 'midnight'
     - 'midnight_blue'
     - 'midnight-orig'
     - 'midnight-remake'
     - 'navy-blue-yellow'
     - 'night-theme'
     - 'noctis'
     - 'noctis-grey'
     - 'oled'
     - 'Orange Dark'
     - 'Orange light'
     - 'oxfordblue'
     - 'pmxmononight'
     - 'purple'
     - 'reeder_dark'
     - 'slate'
     - 'slate_red'
     - 'solarized_light'
     - 'solarized-dark'
     - 'sundown'
     - 'sweetpink'
     - 'synthwave'
     - 'teal'
     - 'uglychristmas'
     - 'ux_goodie'
     - 'vaporwave-pink'
     - 'vintage'
    initial: 'Google Dark Theme'
    icon: 'mdi:palette'

automation:
  - id: 'themestartup'
    alias: 'System - Set Custom Theme at Startup'
    trigger:
      platform: homeassistant
      event: start
    action:
      service: frontend.set_theme
      data:
        name: 'Google Dark Theme'
  - id: 'changetheme'
    alias: 'System - Change Current Theme'
    hide_entity: true
    trigger:
      - platform: state
        entity_id: input_select.theme_switcher
    action:
      - service: frontend.set_theme
        data_template:
          name: "{{states('input_select.theme_switcher')}}"
