# Moon & Seasons
# Need the Moon Phase Icons and Season Icons
# See my Github https://github.com/DavidFW1960/home-assistant/tree/master/www/icons
# Note also that for the Moon Icons, by default these are set for the Southern Hemisphere.
# See that the jpg files all start with an 'S'. For Northern Hemisphere, change these to 'N'

# Track the sun
sun:
  monitored_conditions:
    - azimuth
    - elevation
    - next_dawn
    - next_dusk
    - next_midnight
    - next_noon
    - daylight
    - next_daylight
    - prev_daylight
    - sunrise
    - sunset
  scan_interval:
    minutes: 1

sensor:
  - platform: moon
  - platform: yr
  - platform: template
    sensors:
      yrwthr:
        value_template: '{%set list2 = "0","Clear Sky","Fair","Partly Cloudy","Cloudy","Rain Showers","Rain Showers And Thunder","Sleet Showers","Snow Showers","Rain","Heavy Rain","Heavy Rain And Thunder","Sleet","Snow","Snow And Thunder","Fog","0","0","0","0","Sleet Showers And Thunder","Snow Showers And Thunder","Rain And Thunder","Sleet And Thunder","Light Rain Showers And Thunder","Heavy Rain Showers And Thunder","Light Sleet Showers And Thunder","Heavy Sleet Showers And Thunder","Light Snow Showers And Thunder","Heavy Snow Showers And Thunder","Light Rain And Thunder","Light Sleet And Thunder","Heavy Sleet And Thunder","Light Snow And Thunder","Heavy Snow And Thunder","0","0","0","0","0","Light Rain Showers","Heavy Rain Showers","Light Sleet Showers","Heavy Sleet Showers","Light Snow Showers","Heavy Snow Showers","Light Rain","Light Sleet","Heavy Sleet","Light Snow","Heavy Snow"%}{{list2[states.sensor.yr_symbol.state|int]}}'
        entity_picture_template: "{{ state_attr('sensor.yr_symbol','entity_picture') }}"
      nextsunrise:
        friendly_name: 'Next Sunrise'
        value_template: >
          {{ as_timestamp(states.sun.sun.attributes.next_rising) | timestamp_custom(' %I:%M %p') | replace(" 0", "") }}
        icon_template: mdi:weather-sunset-up
      nextsunset:
        friendly_name: 'Next Sunset'
        value_template: >
          {{ as_timestamp(states.sun.sun.attributes.next_setting) | timestamp_custom(' %I:%M %p') | replace(" 0", "") }}
        icon_template: mdi:weather-sunset-down
      sunrisetoday:
        friendly_name: 'Sunrise'
        value_template: >
          {{ as_timestamp(states.sun.sun.attributes.sunrise) | timestamp_custom(' %I:%M %p') | replace(" 0", "") }}
        icon_template: mdi:weather-sunset-up
      sunsettoday:
        friendly_name: 'Sunset'
        value_template: >
          {{ as_timestamp(states.sun.sun.attributes.sunset) | timestamp_custom(' %I:%M %p') | replace(" 0", "") }}
        icon_template: mdi:weather-sunset-down
      daylightyesterday:
        friendly_name: 'Day Length Yesterday'
        value_template: >
          {{ (states.sun.sun.attributes.prev_daylight) | timestamp_custom(' %H:%M:%S',false) | replace(" 0", "") }}
        icon_template: mdi:weather-sunny
      daylighttoday:
        friendly_name: 'Day Length Today'
        value_template: >
          {{ (states.sun.sun.attributes.daylight) | timestamp_custom(' %H:%M:%S',false) | replace(" 0", "") }}
        icon_template: mdi:weather-sunny
      decimaldaylengthtoday:
        friendly_name: 'Decimal Hours Daylength Today'
        unit_of_measurement: "hours"
        value_template: >
          {{ (state_attr('sun.sun', 'daylight') / (60*60)) | round(2) }}
        icon_template: mdi:weather-sunny
      daylighttomorrow:
        friendly_name: 'Day Length Tomorrow'
        value_template: >
          {{ (states.sun.sun.attributes.next_daylight) | timestamp_custom(' %H:%M:%S',false) | replace(" 0", "") }}
        icon_template: mdi:weather-sunny
      daylengthchange:
        friendly_name: 'Change in Day Length'
        unit_of_measurement: "sec"
        value_template: >
          {{ (states.sun.sun.attributes.daylight) - (states.sun.sun.attributes.prev_daylight) }}
        icon_template: mdi:weather-sunny
      moonphases:
        entity_id: sensor.moon
        friendly_name: 'Moon'
        value_template: >
          {{ states('sensor.moon').title().replace('_',' ') }}
        entity_picture_template: >
          {% set state = states('sensor.moon').title().replace('_','').replace(' ','') %}
          {{ '/local/icons/MoonPhases/S{}.jpg'.format(state) }}
      seasonname:
        entity_id: sensor.season
        friendly_name: 'Season'
        value_template: >
          {{ states('sensor.season').title() }} 
        entity_picture_template: >-
          {% set state = states('sensor.season'.title()) %}
          {{ '/local/icons/season/{}.png'.format(state) }}

# Graph Day Length Change
history_graph:
  lencha:
    name: Day Length Change
    entities:
      - sensor.daylengthchange        
    hours_to_show: 168
    refresh: 1800

group:
  time_tides:
    name: Season, Sun & Moon Phase
    view: no
    icon: mdi:sun
    entities:
      - sensor.seasonname
      - sun.sun
      - sensor.sunrisetoday
      - sensor.sunsettoday
      - sensor.nextsunrise
      - sensor.nextsunset
      - sensor.daylightyesterday
      - sensor.daylighttoday
      - sensor.daylighttomorrow
      - history_graph.day_length_change
      - sensor.yrwthr
      - sensor.moonphases
