# Moon & Seasons
# Need the Moon Phase Icons and Season Icons
# See my Github https://github.com/DavidFW1960/home-assistant/tree/master/www/icons

sensor:
  - platform: moon
  - platform: yr
  - platform: template
    sensors:
      yrwthr:
        value_template: '{%set list2 = "0","Clear Sky","Fair","Partly Cloudy","Cloudy","Rain Showers","Rain Showers And Thunder","Sleet Showers","Snow Showers","Rain","Heavy Rain","Heavy Rain And Thunder","Sleet","Snow","Snow And Thunder","Fog","0","0","0","0","Sleet Showers And Thunder","Snow Showers And Thunder","Rain And Thunder","Sleet And Thunder","Light Rain Showers And Thunder","Heavy Rain Showers And Thunder","Light Sleet Showers And Thunder","Heavy Sleet Showers And Thunder","Light Snow Showers And Thunder","Heavy Snow Showers And Thunder","Light Rain And Thunder","Light Sleet And Thunder","Heavy Sleet And Thunder","Light Snow And Thunder","Heavy Snow And Thunder","0","0","0","0","0","Light Rain Showers","Heavy Rain Showers","Light Sleet Showers","Heavy Sleet Showers","Light Snow Showers","Heavy Snow Showers","Light Rain","Light Sleet","Heavy Sleet","Light Snow","Heavy Snow"%}{{list2[states.sensor.yr_symbol.state|int]}}'
        entity_picture_template: "{{ state_attr('sensor.yr_symbol','entity_picture') }}"
      nextsunrise:
        friendly_name: 'Next Sunrise'
        value_template: >
          {{ as_timestamp(states.sun.sun.attributes.next_rising) | timestamp_custom(' %I:%M%p') | replace(" 0", "") }}
        icon_template: mdi:weather-sunset-up
      nextsunset:
        friendly_name: 'Next Sunset'
        value_template: >
          {{ as_timestamp(states.sun.sun.attributes.next_setting) | timestamp_custom(' %I:%M%p') | replace(" 0", "") }}
        icon_template: mdi:weather-sunset-down
#      daylight:
#        friendly_name: 'Daylight Hours'
#        value_template: >
#          {% set nr = as_timestamp(state_attr('sun.sun','next_rising')) %}
#          {% set ns = as_timestamp(state_attr('sun.sun','next_setting')) %}
#          {% if nr > ns %}
#            {% set nr = nr - 60*60*24 %}
#          {% endif %}
#          {{ (ns - nr)|timestamp_custom('%H:%M',false) }}
#        icon_template: mdi:weather-sunny
      moonphases:
        entity_id: sensor.moon
        friendly_name: 'Moon'
        value_template: >
          {{ states.sensor.moon.state }}
        entity_picture_template: >-
          {% if is_state('sensor.moon', 'New moon') %}
            /local/icons/MoonPhases/SNewMoon.jpg
          {% elif is_state('sensor.moon', 'Waxing crescent') %}
            /local/icons/MoonPhases/SWaxingCrescent.jpg
          {% elif is_state('sensor.moon', 'First quarter') %}
            /local/icons/MoonPhases/SFirstQuarter.jpg
          {% elif is_state('sensor.moon', 'Waxing gibbous') %}
            /local/icons/MoonPhases/SWaxingGibbous.jpg
          {% elif is_state('sensor.moon', 'Full moon') %}
            /local/icons/MoonPhases/SFullMoon.jpg
          {% elif is_state('sensor.moon', 'Waning gibbous') %}
            /local/icons/MoonPhases/SWaningGibbous.jpg
          {% elif is_state('sensor.moon', 'Last quarter') %}
            /local/icons/MoonPhases/SLastQuarter.jpg
          {% elif is_state('sensor.moon', 'Waning crescent') %}
            /local/icons/MoonPhases/SWaningCrescent.jpg
          {% endif %}
      seasonname:
        entity_id: sensor.season
        friendly_name: 'Season'
        value_template: >
          {{ states.sensor.season.state }}
        entity_picture_template: >-
          {% if is_state('sensor.season', 'winter') %}
            /local/icons/season/winter.png
          {% elif is_state('sensor.season', 'spring') %}
            /local/icons/season/spring.png
          {% elif is_state('sensor.season', 'summer') %}
            /local/icons/season/summer.png
          {% elif is_state('sensor.season', 'autumn') %}
            /local/icons/season/autumn.png
          {% endif %}
  - platform: rest
    resource: !secret daylength_yesterday
    name: "Day Length Yesterday (sunrise-sunset.org)"
    value_template: "{{ value_json.results.day_length }}"
    scan_interval:
      minutes: 10
  - platform: rest
    resource: !secret daylength_today
    name: "Day Length Today (sunrise-sunset.org)"
    value_template: "{{ value_json.results.day_length }}"
    scan_interval:
      minutes: 10
  - platform: rest
    resource: !secret daylength_tomorrow
    name: "Day Length Tomorrow (sunrise-sunset.org)"
    value_template: "{{ value_json.results.day_length }}"
    scan_interval:
      minutes: 10
group:
  time_tides:
    name: Season, Sun & Moon Phase
    view: no
    icon: mdi:sun
    entities:
      - sensor.seasonname
      - sun.sun
      - sensor.nextsunrise
      - sensor.nextsunset
      - sensor.day_length_yesterday_sunrisesunsetorg
      - sensor.day_length_today_sunrisesunsetorg
      - sensor.day_length_tomorrow_sunrisesunsetorg
      - sensor.yrwthr
      - sensor.moonphases
