# Public Transport NSW
sensor:
  - platform: transport_nsw
    name: 'Kariong-Gosford'
    stop_id: '2250275'
    api_key: !secret trans_nsw
  - platform: transport_nsw
    name: 'Gosford-Kariong'
    stop_id: '225042'
    api_key: !secret trans_nsw
  - platform: transport_nsw
    name: 'Gosford-Central'
    stop_id: '2250791'
    route: 'Central Coast & Newcastle Line'
    destination: 'Central via Strathfield'
    api_key: !secret trans_nsw
  - platform: transport_nsw
    name: 'Central-Gosford'
    stop_id: '2000329'
    route: 'Central Coast & Newcastle Line'
    destination: 'Newcastle Interchange via Strathfield'
    api_key: !secret trans_nsw
  - platform: template
    sensors:
      busmonitor1:
        friendly_name: "Bus Kariong to Gosford"
        value_template: >-
          {% if is_state_attr('sensor.kariong_gosford', 'due', 'n/a') %}
            No schedule found
          {% else %}
            {{ states.sensor.kariong_gosford.attributes.route }} in {{ states.sensor.kariong_gosford.attributes.due }}m ({{ states.sensor.kariong_gosford.attributes.delay }}m delay)
          {% endif %}
  - platform: template
    sensors:
      busmonitor2:
        friendly_name: "Bus Gosford to Kariong"
        value_template: >-
          {% if is_state_attr('sensor.gosford_kariong', 'due', 'n/a') %}
            No schedule found
          {% else %}
            {{ states.sensor.gosford_kariong.attributes.route }} in {{ states.sensor.gosford_kariong.attributes.due }}m ({{ states.sensor.gosford_kariong.attributes.delay }}m delay)
          {% endif %}
  - platform: template
    sensors:
      trainmonitor1:
        friendly_name: "Train Gosford to Central"
        value_template: >-
          {% if is_state_attr('sensor.gosford_central', 'due', 'n/a') %}
            No schedule found
          {% else %}
            {{ states.sensor.gosford_central.attributes.route }} in {{ states.sensor.gosford_central.attributes.due }}m ({{ states.sensor.gosford_central.attributes.delay }}m delay)
          {% endif %}
  - platform: template
    sensors:
      trainmonitor2:
        friendly_name: "Train Central to Gosford"
        value_template: >-
          {% if is_state_attr('sensor.central_gosford', 'due', 'n/a') %}
            No schedule found
          {% else %}
            {{ states.sensor.central_gosford.attributes.route }} in {{ states.sensor.central_gosford.attributes.due }}m ({{ states.sensor.central_gosford.attributes.delay }}m delay)
          {% endif %}
