################################################
## Packages / Host / Updates
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'updates'

    ################################################
    ## Binary Sensor
    ################################################

    binary_sensor.hass_update_available:
      <<: *customize
      friendly_name: 'Update Available Home Assistant'
      device_class: problem

    ################################################
    ## Sensor
    ################################################

    sensor.hass_installed_version:
      <<: *customize
      friendly_name: 'HA Supervised Installed Version'
      icon: mdi:check-decagram

    sensor.ha_os_agent_installed_version:
      <<: *customize
      friendly_name: 'HA OS-Agent Installed Version'
      icon: mdi:check-decagram

    sensor.hass_available_to_install_version:
      <<: *customize
      friendly_name: 'HA Supervised Available Version Sensor'
      icon: mdi:check-decagram

    sensor.current_ha_beta:
      <<: *customize
      friendly_name: 'HA Supervised Beta Version'
      icon: mdi:beta

    sensor.current_ha_stable:
      <<: *customize
      friendly_name: 'HA Supervised Current Stable Version'
      icon: mdi:check-decagram

    sensor.current_ha_dev:
      <<: *customize
      friendly_name: 'HA Supervised Dev Version'
      icon: mdi:alpha

    sensor.current_supervisor_beta:
      <<: *customize
      friendly_name: 'HA Current Supervisor Beta'
      icon: mdi:beta

    sensor.current_supervisor_stable:
      <<: *customize
      friendly_name: 'HA Current Supervisor Stable'
      icon: mdi:check-decagram

    sensor.current_supervisor_installed:
      <<: *customize
      friendly_name: 'HA Current Supervisor Installed'
      icon: mdi:check-decagram

    sensor.current_supervisor_dev:
      <<: *customize
      friendly_name: 'HA Current Supervisor Dev'
      icon: mdi:alpha

    sensor.current_hassos_beta:
      <<: *customize
      friendly_name: 'HassOS Current Beta'
      icon: mdi:beta

    sensor.current_hassos_stable:
      <<: *customize
      friendly_name: 'HassOS Current Stable'
      icon: mdi:check-decagram

    sensor.current_hassos_dev:
      <<: *customize
      friendly_name: 'HassOS Current Dev'
      icon: mdi:alpha

    sensor.current_dns_beta:
      <<: *customize
      friendly_name: 'DNS Current Beta'
      icon: mdi:beta

    sensor.current_dns_stable:
      <<: *customize
      friendly_name: 'DNS Current Stable'
      icon: mdi:check-decagram

    sensor.current_dns_installed:
      <<: *customize
      friendly_name: 'DNS Current Installed'
      icon: mdi:check-decagram

    sensor.current_dns_dev:
      <<: *customize
      friendly_name: 'DNS Current Dev'
      icon: mdi:alpha

    sensor.current_audio_beta:
      <<: *customize
      friendly_name: 'Audio Current Beta'
      icon: mdi:beta

    sensor.current_audio_stable:
      <<: *customize
      friendly_name: 'Audio Current Stable'
      icon: mdi:check-decagram

    sensor.current_audio_installed:
      <<: *customize
      friendly_name: 'Audio Current Installed'
      icon: mdi:check-decagram

    sensor.current_audio_dev:
      <<: *customize
      friendly_name: 'Audio Current Dev'
      icon: mdi:alpha

    sensor.current_hassos_cli_beta:
      <<: *customize
      friendly_name: 'HassOS Cli Current Beta'
      icon: mdi:beta

    sensor.current_hassos_cli_stable:
      <<: *customize
      friendly_name: 'HassOS Cli Current Stable'
      icon: mdi:check-decagram

    sensor.current_hassos_cli_dev:
      <<: *customize
      friendly_name: 'HassOS Cli Current Dev'
      icon: mdi:alpha
    sensor.current_cli_beta:
      <<: *customize
      friendly_name: 'Cli Current Beta'
      icon: mdi:beta

    sensor.current_cli_stable:
      <<: *customize
      friendly_name: 'Cli Current Stable'
      icon: mdi:check-decagram

    sensor.current_cli_dev:
      <<: *customize
      friendly_name: 'Cli Current Dev'
      icon: mdi:alpha

    sensor.current_cli_installed:
      <<: *customize
      friendly_name: 'Cli Current Installed'
      icon: mdi:check-decagram

    sensor.current_multicast_latest:
      <<: *customize
      friendly_name: 'Multicast Latest'
      icon: mdi:check-decagram

    sensor.current_multicast_installed:
      <<: *customize
      friendly_name: 'Multicast Installed'
      icon: mdi:check-decagram

    sensor.current_observer_latest:
      <<: *customize
      friendly_name: 'Observer Latest'
      icon: mdi:check-decagram

    sensor.current_observer_installed:
      <<: *customize
      friendly_name: 'Observer Installed'
      icon: mdi:check-decagram

################################################
## Sensor
################################################

sensor:
  - platform: command_line
    name: Hass Installed Version
    command: "cat /config/.HA_VERSION"

  - platform: mqtt
    name: "HA OS-Agent Installed Version"
    state_topic: "haosagentinstalled"
    value_template: "{{ value_json.state }}"

  - platform: command_line
    name: Supervisor Installed
    command: 'curl http://supervisor/supervisor/info -H "Authorization: Bearer $(printenv SUPERVISOR_TOKEN)" | jq ''{"newest_version":.data.version_latest,"current_version":.data.version,"update_available":.data.update_available,"addons":[.data.addons[] | select(.update_available)]}'''
    value_template: "{{ value_json.addons | length }}"
    unit_of_measurement: pending update(s)
    json_attributes:
      - update_available
      - newest_version
      - current_version
      - addons

  - platform: command_line
    name: DNS Installed
    command: 'curl http://supervisor/dns/info -H "Authorization: Bearer $(printenv SUPERVISOR_TOKEN)" | jq ''{"version":.data.version,"version_latest":.data.version_latest }'''
    value_template: "{{ value_json.version }}"
    json_attributes:
      - version
      - version_latest

  - platform: command_line
    name: Audio Installed
    command: 'curl http://supervisor/audio/info -H "Authorization: Bearer $(printenv SUPERVISOR_TOKEN)" | jq ''{"version":.data.version,"version_latest":.data.version_latest }'''
    value_template: "{{ value_json.version }}"
    json_attributes:
      - version
      - version_latest

  - platform: command_line
    name: Cli Installed
    command: 'curl http://supervisor/cli/info -H "Authorization: Bearer $(printenv SUPERVISOR_TOKEN)" | jq ''{"version":.data.version,"version_latest":.data.version_latest }'''
    value_template: "{{ value_json.version }}"
    json_attributes:
      - version
      - version_latest

  - platform: command_line
    name: Multicast Installed
    command: 'curl http://supervisor/multicast/info -H "Authorization: Bearer $(printenv SUPERVISOR_TOKEN)" | jq ''{"version":.data.version,"version_latest":.data.version_latest }'''
    value_template: "{{ value_json.version }}"
    json_attributes:
      - version
      - version_latest

  - platform: command_line
    name: Observer Installed
    command: 'curl http://supervisor/observer/info -H "Authorization: Bearer $(printenv SUPERVISOR_TOKEN)" | jq ''{"host": .data.host,"version":.data.version,"version_latest":.data.version_latest }'''
    value_template: "{{ value_json.version }}"
    json_attributes:
      - host
      - version
      - version_latest

  - platform: template
    sensors:
      current_supervisor_installed:
        value_template: '{{ states.sensor.supervisor_installed.attributes["current_version"] }}'
      current_dns_installed:
        value_template: '{{ states.sensor.dns_installed.attributes["version"] }}'
      current_audio_installed:
        value_template: '{{ states.sensor.audio_installed.attributes["version"] }}'
      current_cli_installed:
        value_template: '{{ states.sensor.cli_installed.attributes["version"] }}'
      current_multicast_installed:
        value_template: '{{ states.sensor.multicast_installed.attributes["version"] }}'
      current_multicast_latest:
        value_template: '{{ states.sensor.multicast_installed.attributes["version_latest"] }}'
      current_observer_installed:
        value_template: '{{ states.sensor.observer_installed.attributes["version"] }}'
      current_observer_latest:
        value_template: '{{ states.sensor.observer_installed.attributes["version_latest"] }}'

  - platform: rest
    resource: https://version.home-assistant.io/beta.json
    name: Home Assistant Beta Supervised Versions
    scan_interval: 7200
    json_attributes:
      - supervisor
      - homeassistant
      - hassos
      - cli
      - dns
      - audio
    value_template: 'OK'
  - platform: template
    sensors:
      current_supervisor_beta:
        value_template: '{{ states.sensor.home_assistant_beta_supervised_versions.attributes["supervisor"] }}'
      current_ha_beta:
        value_template: '{{ states.sensor.home_assistant_beta_supervised_versions.attributes["homeassistant"]["generic-x86-64"] }}'
      current_hassos_beta:
        value_template: '{{ states.sensor.home_assistant_beta_supervised_versions.attributes["hassos"]["generic-x86-64"] }}'
      current_cli_beta:
        value_template: '{{ states.sensor.home_assistant_beta_supervised_versions.attributes["cli"] }}'
      current_dns_beta:
        value_template: '{{ states.sensor.home_assistant_beta_supervised_versions.attributes["dns"] }}'
      current_audio_beta:
        value_template: '{{ states.sensor.home_assistant_beta_supervised_versions.attributes["audio"] }}'
  - platform: rest
    resource: https://version.home-assistant.io/stable.json
    name: Home Assistant Supervised Stable Versions
    scan_interval: 7200
    json_attributes:
      - supervisor
      - homeassistant
      - hassos
      - cli
      - dns
      - audio
    value_template: 'OK'
  - platform: template
    sensors:
      current_supervisor_stable:
        value_template: '{{ states.sensor.home_assistant_supervised_stable_versions.attributes["supervisor"] }}'
      current_ha_stable:
        value_template: '{{ states.sensor.home_assistant_supervised_stable_versions.attributes["homeassistant"]["generic-x86-64"] }}'
      current_hassos_stable:
        value_template: '{{ states.sensor.home_assistant_supervised_stable_versions.attributes["hassos"]["generic-x86-64"] }}'
      current_cli_stable:
        value_template: '{{ states.sensor.home_assistant_supervised_stable_versions.attributes["cli"] }}'
      current_dns_stable:
        value_template: '{{ states.sensor.home_assistant_supervised_stable_versions.attributes["dns"] }}'
      current_audio_stable:
        value_template: '{{ states.sensor.home_assistant_supervised_stable_versions.attributes["audio"] }}'
  - platform: rest
    resource: https://version.home-assistant.io/dev.json
    name: Home Assistant Supervised Dev Versions
    scan_interval: 7200
    json_attributes:
      - supervisor
      - homeassistant
      - hassos
      - cli
      - dns
      - audio
    value_template: 'OK'
  - platform: template
    sensors:
      current_supervisor_dev:
        value_template: '{{ states.sensor.home_assistant_supervised_dev_versions.attributes["supervisor"] }}'
      current_ha_dev:
        value_template: '{{ states.sensor.home_assistant_supervised_dev_versions.attributes["homeassistant"]["generic-x86-64"] }}'
      current_hassos_dev:
        value_template: '{{ states.sensor.home_assistant_supervised_dev_versions.attributes["hassos"]["generic-x86-64"] }}'
      current_cli_dev:
        value_template: '{{ states.sensor.home_assistant_supervised_dev_versions.attributes["cli"] }}'
      current_dns_dev:
        value_template: '{{ states.sensor.home_assistant_supervised_dev_versions.attributes["dns"] }}'
      current_audio_dev:
        value_template: '{{ states.sensor.home_assistant_supervised_dev_versions.attributes["audio"] }}'

################################################
## Binary Sensor
################################################

binary_sensor:
  - platform: template
    sensors:
      hass_update_available:
        value_template: >-
           {%- if states('sensor.current_ha_stable') != 'unavailable' -%}
           {% set next = states('sensor.current_ha_stable') %}
           {% set current = states('sensor.hass_installed_version') | replace('b','.') %}
           {{ next.split('.') | map('int', 0) | list >  current.split('.') | map('int', 0) | list }}
           {%- endif %}
################################################
## Automation
################################################

automation:
  - alias: 'Update Available'
    id: 'updateavailable'
    trigger:
      - platform: template
        value_template: >-
          {{ states('sensor.current_ha_stable') != 'unavailable' and 
             states('sensor.current_ha_stable') > states('sensor.hass_installed_version')
             }}
    action:
      - service: notify.david_ios_notify
        data:
          message: "Home Assistant version {{ states('sensor.current_ha_stable') }} is now available for HA Supervised"
          title: Home Assistant Update
  - alias: 'Beta Update Available'
    id: 'BetaUpdateAvailable'
    trigger:
      - platform: template
        value_template: >-
          {{ states('sensor.current_ha_beta') != 'unavailable' and 
             states('sensor.current_ha_beta') > states('sensor.hass_installed_version')
             }}
    action:
      - service: notify.david_ios_notify
        data:
          message: "Home Assistant Beta version {{ states('sensor.current_ha_beta') }} is now available for HA Supervised"
          title: Home Assistant Beta Update

################################################
## CLI Commands
################################################
# ha su options --channel dev
