################################################
## Packages / Host / Updates
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'updates'

    ################################################
    ## Binary Sensor
    ################################################

    binary_sensor.hass_update_available:
      <<: *customize
      friendly_name: 'Update Available Hass'
      device_class: problem

    ################################################
    ## Sensor
    ################################################

    sensor.hass_installed_version:
      <<: *customize
      friendly_name: 'Hass.io Installed Version'
      icon: mdi:check-decagram

    sensor.hass_current_stable_version:
      <<: *customize
      friendly_name: 'Hass.io Current Stable Version'
      icon: mdi:check-decagram

    sensor.hass_current_beta_version:
      <<: *customize
      friendly_name: 'Hass.io Beta Release'
      icon: mdi:beta

    sensor.hass_current_dev_version:
      <<: *customize
      friendly_name: 'Hass.io Dev Release'
      icon: mdi:alpha

    sensor.hass_current_supervisor_version:
      <<: *customize
      friendly_name: 'Hass.io Current Supervisor Version'
      icon: mdi:check-decagram

    sensor.hass_current_hassos_version:
      <<: *customize
      friendly_name: 'Hass.io Current HassOS Version'
      icon: mdi:check-decagram

################################################
## Updater
## https://www.home-assistant.io/components/updater/
## https://www.home-assistant.io/docs/backend/updater/
################################################

updater:
  reporting: true # collect basic information about this instance and its environment
  include_used_components: true # report components to developers

################################################
## Sensor
################################################

sensor:
  - platform: version
    name: Hass Installed Version

  - platform: rest
    resource: https://s3.amazonaws.com/hassio-version/stable.json
    name: Hass Current Stable Version
    value_template: '{{ value_json.homeassistant.raspberrypi3 }}'

  - platform: rest
    resource: https://s3.amazonaws.com/hassio-version/beta.json
    name: Hass Current Beta Version
    value_template: '{{ value_json.homeassistant.raspberrypi3 }}'

  - platform: rest
    resource: https://s3.amazonaws.com/hassio-version/dev.json
    name: Hass Current Dev Version
    value_template: '{{ value_json.homeassistant.raspberrypi3 }}'

  - platform: rest
    resource: https://s3.amazonaws.com/hassio-version/stable.json
    name: Hass Current Supervisor Version
    value_template: '{{ value_json.supervisor }}'

  - platform: rest
    resource: https://s3.amazonaws.com/hassio-version/stable.json
    name: Hass Current HassOS Version
    value_template: '{{ value_json.hassos.rpi3 }}'

################################################
## Binary Sensor
################################################

binary_sensor:
  - platform: template
    sensors:
      hass_update_available:
        value_template: >-
          {{ states.sensor.hass_current_stable_version.state != 'unavailable' and 
             states.sensor.hass_current_stable_version.state > states.sensor.hass_installed_version.state
              }}
group:
  host_updates:
    name: 'Updates'
    entities:
      - updater.updater
      - sensor.hass_installed_version
      - sensor.hass_current_stable_version
      - sensor.hass_current_beta_version
      - sensor.hass_current_dev_version
      - sensor.hass_current_supervisor_version
      - binary_sensor.hass_update_available

################################################
## Automation
################################################

automation:
  - alias: 'Update Available'
    initial_state: 'on'
    trigger:
      - platform: template
        value_template: >-
          {{ states.sensor.hass_current_stable_version.state != 'unavailable' and 
             states.sensor.hass_current_stable_version.state > states.sensor.hass_installed_version.state
             }}
    action:
      - service: notify.admin
        data:
          message: 'Home Assistant version {{ states.sensor.hass_current_stable_version.state }} is now available for Hass.io'
          title: Home Assistant Update
