################################################
## Packages / Host / Updates
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'updates'

    ################################################
    ## Binary Sensor
    ################################################

    binary_sensor.hass_update_available:
      <<: *customize
      friendly_name: 'Update Available Hass'
      device_class: problem

    ################################################
    ## Sensor
    ################################################

    sensor.hass_installed_version:
      <<: *customize
      friendly_name: 'HA Supervised Installed Version'
      icon: mdi:check-decagram

    sensor.hass_available_to_install_version:
      <<: *customize
      friendly_name: 'HA Supervised Available Version Sensor'
      icon: mdi:check-decagram

    sensor.current_ha_beta:
      <<: *customize
      friendly_name: 'HA Supervised Beta Version'
      icon: mdi:beta

    sensor.current_ha_stable:
      <<: *customize
      friendly_name: 'HA Supervised Current Stable Version'
      icon: mdi:check-decagram

    sensor.current_ha_dev:
      <<: *customize
      friendly_name: 'Hass.io Dev Release'
      icon: mdi:alpha

    sensor.current_supervisor_beta:
      <<: *customize
      friendly_name: 'HA Current Supervisor Beta'
      icon: mdi:beta

    sensor.current_supervisor_stable:
      <<: *customize
      friendly_name: 'HA Current Supervisor Stable'
      icon: mdi:check-decagram

    sensor.current_supervisor_dev:
      <<: *customize
      friendly_name: 'HA Current Supervisor Beta'
      icon: mdi:alpha

    sensor.current_hassos_beta:
      <<: *customize
      friendly_name: 'HassOS Current Beta'
      icon: mdi:beta

    sensor.current_hassos_stable:
      <<: *customize
      friendly_name: 'HassOS Current Stable'
      icon: mdi:check-decagram

    sensor.current_hassos_dev:
      <<: *customize
      friendly_name: 'HassOS Current Dev'
      icon: mdi:alpha

    sensor.current_dns_beta:
      <<: *customize
      friendly_name: 'DNS Current Beta'
      icon: mdi:beta

    sensor.current_dns_stable:
      <<: *customize
      friendly_name: 'DNS Current Stable'
      icon: mdi:check-decagram

    sensor.current_dns_dev:
      <<: *customize
      friendly_name: 'DNS Current Dev'
      icon: mdi:alpha

    sensor.current_audio_beta:
      <<: *customize
      friendly_name: 'Audio Current Beta'
      icon: mdi:beta

    sensor.current_audio_stable:
      <<: *customize
      friendly_name: 'Audio Current Stable'
      icon: mdi:check-decagram

    sensor.current_audio_dev:
      <<: *customize
      friendly_name: 'Audio Current Dev'
      icon: mdi:alpha

    sensor.current_hassos_cli_beta:
      <<: *customize
      friendly_name: 'HassOS Cli Current Beta'
      icon: mdi:beta

    sensor.current_hassos_cli_stable:
      <<: *customize
      friendly_name: 'HassOS Cli Current Stable'
      icon: mdi:check-decagram

    sensor.current_hassos_cli_dev:
      <<: *customize
      friendly_name: 'HassOS Cli Current Dev'
      icon: mdi:alpha
    sensor.current_cli_beta:
      <<: *customize
      friendly_name: 'Cli Current Beta'
      icon: mdi:beta

    sensor.current_cli_stable:
      <<: *customize
      friendly_name: 'Cli Current Stable'
      icon: mdi:check-decagram

    sensor.current_cli_dev:
      <<: *customize
      friendly_name: 'Cli Current Dev'
      icon: mdi:alpha

################################################
## Updater
## https://www.home-assistant.io/components/updater/
## https://www.home-assistant.io/docs/backend/updater/
################################################

updater:
  reporting: true # collect basic information about this instance and its environment
  include_used_components: true # report components to developers

################################################
## Sensor
################################################

sensor:
  - platform: command_line
    name: Hass Installed Version
    command: "cat /config/.HA_VERSION"

  - platform: version
    name: Hass Available to Install Version
    beta: true
    image: qemux86-64
    source: hassio

  - platform: rest
    resource: https://s3.amazonaws.com/hassio-version/beta.json
    name: Home Assistant Beta Supervised Versions
    scan_interval: 7200
    json_attributes:
      - supervisor
      - homeassistant
      - hassos
      - hassos-cli
      - cli
      - dns
      - audio
    value_template: 'OK'
  - platform: template
    sensors:
      current_supervisor_beta:
        value_template: '{{ states.sensor.home_assistant_beta_supervised_versions.attributes["supervisor"] }}'
      current_ha_beta:
        value_template: '{{ states.sensor.home_assistant_beta_supervised_versions.attributes["homeassistant"]["intel-nuc"] }}'
      current_hassos_beta:
        value_template: '{{ states.sensor.home_assistant_beta_supervised_versions.attributes["hassos"]["intel-nuc"] }}'
      current_hassos_cli_beta:
        value_template: '{{ states.sensor.home_assistant_beta_supervised_versions.attributes["hassos-cli"] }}'
      current_cli_beta:
        value_template: '{{ states.sensor.home_assistant_beta_supervised_versions.attributes["cli"] }}'
      current_dns_beta:
        value_template: '{{ states.sensor.home_assistant_beta_supervised_versions.attributes["dns"] }}'
      current_audio_beta:
        value_template: '{{ states.sensor.home_assistant_beta_supervised_versions.attributes["audio"] }}'
  - platform: rest
    resource: https://s3.amazonaws.com/hassio-version/stable.json
    name: Home Assistant Supervised Stable Versions
    scan_interval: 7200
    json_attributes:
      - supervisor
      - homeassistant
      - hassos
      - hassos-cli
      - cli
      - dns
      - audio
    value_template: 'OK'
  - platform: template
    sensors:
      current_supervisor_stable:
        value_template: '{{ states.sensor.home_assistant_supervised_stable_versions.attributes["supervisor"] }}'
      current_ha_stable:
        value_template: '{{ states.sensor.home_assistant_supervised_stable_versions.attributes["homeassistant"]["intel-nuc"] }}'
      current_hassos_stable:
        value_template: '{{ states.sensor.home_assistant_supervised_stable_versions.attributes["hassos"]["intel-nuc"] }}'
      current_hassos_cli_stable:
        value_template: '{{ states.sensor.home_assistant_supervised_stable_versions.attributes["hassos-cli"] }}'
      current_cli_stable:
        value_template: '{{ states.sensor.home_assistant_supervised_stable_versions.attributes["cli"] }}'
      current_dns_stable:
        value_template: '{{ states.sensor.home_assistant_supervised_stable_versions.attributes["dns"] }}'
      current_audio_stable:
        value_template: '{{ states.sensor.home_assistant_supervised_stable_versions.attributes["audio"] }}'
  - platform: rest
    resource: https://s3.amazonaws.com/hassio-version/dev.json
    name: Home Assistant Supervised Dev Versions
    scan_interval: 7200
    json_attributes:
      - supervisor
      - homeassistant
      - hassos
      - hassos-cli
      - cli
      - dns
      - audio
    value_template: 'OK'
  - platform: template
    sensors:
      current_supervisor_dev:
        value_template: '{{ states.sensor.home_assistant_supervised_dev_versions.attributes["supervisor"] }}'
      current_ha_dev:
        value_template: '{{ states.sensor.home_assistant_supervised_dev_versions.attributes["homeassistant"]["intel-nuc"] }}'
      current_hassos_dev:
        value_template: '{{ states.sensor.home_assistant_supervised_dev_versions.attributes["hassos"]["intel-nuc"] }}'
      current_hassos_cli_dev:
        value_template: '{{ states.sensor.home_assistant_supervised_dev_versions.attributes["hassos-cli"] }}'
      current_cli_dev:
        value_template: '{{ states.sensor.home_assistant_supervised_dev_versions.attributes["cli"] }}'
      current_dns_dev:
        value_template: '{{ states.sensor.home_assistant_supervised_dev_versions.attributes["dns"] }}'
      current_audio_dev:
        value_template: '{{ states.sensor.home_assistant_supervised_dev_versions.attributes["audio"] }}'

################################################
## Binary Sensor
################################################

binary_sensor:
  - platform: template
    sensors:
      hass_update_available:
        value_template: >-
          {{ states('sensor.current_ha_stable') != 'unavailable' and 
             states('sensor.current_ha_stable') > states('sensor.hass_installed_version')
              }}

################################################
## Automation
################################################

automation:
  - alias: 'Update Available'
    trigger:
      - platform: template
        value_template: >-
          {{ states('sensor.current_ha_stable') != 'unavailable' and 
             states('sensor.current_ha_stable') > states('sensor.hass_installed_version')
             }}
    action:
      - service: notify.david_ios_notify
        data:
          message: "Home Assistant version {{ states('sensor.current_ha_stable') }} is now available for Hass.io"
          title: Home Assistant Update
  - alias: 'Beta Update Available'
    trigger:
      - platform: template
        value_template: >-
          {{ states('sensor.current_ha_beta') != 'unavailable' and 
             states('sensor.current_ha_beta') > states('sensor.hass_installed_version')
             }}
    action:
      - service: notify.david_ios_notify
        data:
          message: "Home Assistant Beta version {{ states('sensor.current_ha_beta') }} is now available for Hass.io"
          title: Home Assistant Beta Update

################################################
## CLI Commands
################################################
# ha su options --channel dev
