# Download the Dark Sky icons from https://www.dr-lex.be/software/download/DarkSky-icons.zip
# and save them under /www/icons/dark_sky/ in your configuration directory.
# Show BOM Satellite and Radar

camera:
  - platform: generic
    name: BOM Satellite
    still_image_url: http://www.bom.gov.au/gms/IDE00135.jpg
  - platform: bom
    name: Sydney
    id: 714   
    frames: 6
    delta: 360
  - platform: bom
    name: Newcastle
    id: '043'
    frames: 6
    delta: 360

sensor:
  - platform: bom
    station: !secret my_bom_station
    name: !secret my_bom_name
    monitored_conditions:
      - apparent_t
      - delta_t
      - gust_kmh
      - gust_kt
      - air_temp
      - dewpt
      - rain_trace
      - rel_hum
      - wind_dir
      - wind_spd_kmh
      - wind_spd_kt

  - platform: bom_forecast
    product_id: IDN11052
    name: Gosford
    forecast_days: 6
    rest_of_today: true
    friendly: false
    friendly_state_format: '{max}, {summary}'
    monitored_conditions:
      - 'max'
      - 'min'
      - 'chance_of_rain'
      - 'possible_rainfall'
      - 'summary'
      - 'detailed_summary'
      - 'icon'

  - platform: darksky
    api_key: !secret darksky_key
    forecast:
      - 0
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      - 7
    monitored_conditions:
      - icon
      - summary
      - nearest_storm_distance
      - nearest_storm_bearing
      - humidity
      - temperature
      - temperature_high
      - temperature_low
      - apparent_temperature
      - apparent_temperature_high
      - apparent_temperature_low
      - wind_speed
      - wind_bearing
      - precip_type
      - precip_probability
      - precip_accumulation
      - precip_intensity
      - precip_intensity_max
      - uv_index
      - daily_summary
      - pressure
      - visibility
      - dew_point
      - wind_gust
      - cloud_cover
      - ozone
      - minutely_summary
      - hourly_summary
      - moon_phase
      - sunrise_time
      - sunset_time
    scan_interval:
      minutes: 5

  - platform: season

  - platform: template
    sensors:
      forecast_0:
        entity_id:
          - sensor.dark_sky_daytime_high_temperature_0d
          - sensor.dark_sky_overnight_low_temperature_0d
          - sensor.dark_sky_precip_probability_0d
        friendly_name: "Today"
        value_template: >
          {{states('sensor.dark_sky_daytime_high_temperature_0d')|round(0)}}°/{{states('sensor.dark_sky_overnight_low_temperature_0d')|round(0)}}°/{{states('sensor.dark_sky_precip_probability_0d')|round(0)}}%
        entity_picture_template: >-
          {{ '/local/icons/dark_sky/' ~ states('sensor.dark_sky_icon_0d') ~ '.png'}}

      forecast_1:
        entity_id:
          - sensor.dark_sky_daytime_high_temperature_1d
          - sensor.dark_sky_overnight_low_temperature_1d
          - sensor.dark_sky_precip_probability_1d
        friendly_name_template: >
          {%- set date = as_timestamp(now()) + (1 * 86400 ) -%}
          {{ date | timestamp_custom("Tomorrow (%d/%m)") | replace("(0", "(") | replace("/0", "/") }}
        value_template: >
          {{states('sensor.dark_sky_daytime_high_temperature_1d')|round(0)}}°/{{states('sensor.dark_sky_overnight_low_temperature_1d')|round(0)}}°/{{states('sensor.dark_sky_precip_probability_1d')|round(0)}}%
        entity_picture_template: >-
          {{ '/local/icons/dark_sky/' ~ states('sensor.dark_sky_icon_1d') ~ '.png'}}

      forecast_2:
        entity_id:
          - sensor.dark_sky_daytime_high_temperature_2d
          - sensor.dark_sky_overnight_low_temperature_2d
          - sensor.dark_sky_precip_probability_2d
        friendly_name_template: >
          {%- set date = as_timestamp(now()) + (2 * 86400 ) -%}
          {{ date | timestamp_custom("%A (%d/%m)") | replace("(0", "(") | replace("/0", "/") }}
        value_template: >
          {{states('sensor.dark_sky_daytime_high_temperature_2d')|round(0)}}°/{{states('sensor.dark_sky_overnight_low_temperature_2d')|round(0)}}°/{{states('sensor.dark_sky_precip_probability_2d')|round(0)}}%
        entity_picture_template: >-
          {{ '/local/icons/dark_sky/' ~ states('sensor.dark_sky_icon_2d') ~ '.png'}}

      forecast_3:
        entity_id:
          - sensor.dark_sky_daytime_high_temperature_3d
          - sensor.dark_sky_overnight_low_temperature_3d
          - sensor.dark_sky_precip_probability_3d
        friendly_name_template: >
          {%- set date = as_timestamp(now()) + (3 * 86400 ) -%}
          {{ date | timestamp_custom("%A (%d/%m)") | replace("(0", "(") | replace("/0", "/") }}
        value_template: >
          {{states('sensor.dark_sky_daytime_high_temperature_3d')|round(0)}}°/{{states('sensor.dark_sky_overnight_low_temperature_3d')|round(0)}}°/{{states('sensor.dark_sky_precip_probability_3d')|round(0)}}%
        entity_picture_template: >-
          {{ '/local/icons/dark_sky/' ~ states('sensor.dark_sky_icon_3d') ~ '.png'}}

      forecast_4:
        entity_id:
          - sensor.dark_sky_daytime_high_temperature_4d
          - sensor.dark_sky_overnight_low_temperature_4d
          - sensor.dark_sky_precip_probability_4d
        friendly_name_template: >
          {%- set date = as_timestamp(now()) + (4 * 86400 ) -%}
          {{ date | timestamp_custom("%A (%d/%m)") | replace("(0", "(") | replace("/0", "/") }}
        value_template: >
          {{states('sensor.dark_sky_daytime_high_temperature_4d')|round(0)}}°/{{states('sensor.dark_sky_overnight_low_temperature_4d')|round(0)}}°/{{states('sensor.dark_sky_precip_probability_4d')|round(0)}}%
        entity_picture_template: >-
          {{ '/local/icons/dark_sky/' ~ states('sensor.dark_sky_icon_4d') ~ '.png'}}

      forecast_5:
        entity_id:
          - sensor.dark_sky_daytime_high_temperature_5d
          - sensor.dark_sky_overnight_low_temperature_5d
          - sensor.dark_sky_precip_probability_5d
        friendly_name_template: >
          {%- set date = as_timestamp(now()) + (5 * 86400 ) -%}
          {{ date | timestamp_custom("%A (%d/%m)") | replace("(0", "(") | replace("/0", "/") }}
        value_template: >
          {{states('sensor.dark_sky_daytime_high_temperature_5d')|round(0)}}°/{{states('sensor.dark_sky_overnight_low_temperature_5d')|round(0)}}°/{{states('sensor.dark_sky_precip_probability_5d')|round(0)}}%
        entity_picture_template: >-
          {{ '/local/icons/dark_sky/' ~ states('sensor.dark_sky_icon_5d') ~ '.png'}}

      forecast_6:
        entity_id:
          - sensor.dark_sky_daytime_high_temperature_6d
          - sensor.dark_sky_overnight_low_temperature_6d
          - sensor.dark_sky_precip_probability_6d
        friendly_name_template: >
          {%- set date = as_timestamp(now()) + (6 * 86400 ) -%}
          {{ date | timestamp_custom("%A (%d/%m)") | replace("(0", "(") | replace("/0", "/") }}
        value_template: >
            {{states('sensor.dark_sky_daytime_high_temperature_6d')|round(0)}}°/{{states('sensor.dark_sky_overnight_low_temperature_6d')|round(0)}}°/{{states('sensor.dark_sky_precip_probability_6d')|round(0)}}%
        entity_picture_template: >-
          {{ '/local/icons/dark_sky/' ~ states('sensor.dark_sky_icon_6d') ~ '.png'}}

      forecast_7:
        entity_id:
          - sensor.dark_sky_daytime_high_temperature_7d
          - sensor.dark_sky_overnight_low_temperature_7d
          - sensor.dark_sky_precip_probability_7d
        friendly_name_template: >
          {%- set date = as_timestamp(now()) + (7 * 86400 ) -%}
          {{ date | timestamp_custom("%A (%d/%m)") | replace("(0", "(") | replace("/0", "/") }}
        value_template: >
            {{states('sensor.dark_sky_daytime_high_temperature_7d')|round(0)}}°/{{states('sensor.dark_sky_overnight_low_temperature_7d')|round(0)}}°/{{states('sensor.dark_sky_precip_probability_7d')|round(0)}}%
        entity_picture_template: >-
          {{ '/local/icons/dark_sky/' ~ states('sensor.dark_sky_icon_7d') ~ '.png'}}

      dark_sky_current_text:
        value_template: '{% if is_state("sensor.dark_sky_icon","clear-day") %} Clear 
                         {% elif is_state("sensor.dark_sky_icon","clear-night") %} Clear 
                         {% elif is_state("sensor.dark_sky_icon","rain") %} Rain
                         {% elif is_state("sensor.dark_sky_icon","snow") %} Snowy
                         {% elif is_state("sensor.dark_sky_icon","fog") %} Foggy
                         {% elif is_state("sensor.dark_sky_icon","sleet") %} Sleet
                         {% elif is_state("sensor.dark_sky_icon","wind") %} Windy
                         {% elif is_state("sensor.dark_sky_icon","cloudy") %} Cloudy
                         {% elif is_state("sensor.dark_sky_icon","partly-cloudy-day") %} Partly Cloudy
                         {% elif is_state("sensor.dark_sky_icon","partly-cloudy-night") %} Partly Cloudy
                         {% elif is_state("sensor.dark_sky_icon","hail") %} Hailing
                         {% elif is_state("sensor.dark_sky_icon","lightning") %} Lightning
                         {% elif is_state("sensor.dark_sky_icon","thunderstorm") %} Thunderstorm
                         {% endif %}'

      bom_current_text:
        value_template: >
            {% set val = states("sensor.bom_gosford_detailed_summary_0") %} 
            {{ val.split('.')[0] | title }}

      bom_forecast_0:
        entity_id:
          - sensor.bom_today_max
          - sensor.bom_today_min
          - sensor.bom_gosford_chance_of_rain_0
          - sensor.bom_gosford_icon_0
        friendly_name: "Today"
        value_template: >
          {{states('sensor.bom_today_max')|round(0)}}°/{{states('sensor.bom_today_min')|round(0)}}°/{{states('sensor.bom_gosford_chance_of_rain_0')|round(0)}}%
        entity_picture_template: >-
          {%- if now().strftime('%H:%M') > '18:00' and (states('sensor.bom_gosford_icon_0') == 'fog' or states('sensor.bom_gosford_icon_0') == 'haze' or states('sensor.bom_gosford_icon_0') == ' light-showers' or states('sensor.bom_gosford_icon_0') == 'partly-cloudy' or states('sensor.bom_gosford_icon_0') == 'showers') -%}
          {{ '/local/icons/bom_icons/' ~ states('sensor.bom_gosford_icon_0') ~ '-night.png' }}
          {%- else -%}
          {{ '/local/icons/bom_icons/' ~ states('sensor.bom_gosford_icon_0') ~ '.png' }}
          {%- endif -%}

      bom_forecast_1:
        entity_id:
          - sensor.bom_gosford_max_temp_c_1
          - sensor.bom_gosford_min_temp_c_1
          - sensor.bom_gosford_chance_of_rain_1
          - sensor.bom_gosford_icon_1
        friendly_name_template: >
          {%- set date = as_timestamp(now()) + (1 * 86400 ) -%}
          {{ date | timestamp_custom("Tomorrow (%d/%m)") | replace("(0", "(") | replace("/0", "/") }}
        value_template: >
          {{states('sensor.bom_gosford_max_temp_c_1')|round(0)}}°/{{states('sensor.bom_gosford_min_temp_c_1')|round(0)}}°/{{states('sensor.bom_gosford_chance_of_rain_1')|round(0)}}%
        entity_picture_template: >-
          {{ '/local/icons/bom_icons/' ~ states('sensor.bom_gosford_icon_1') ~ '.png' }}

      bom_forecast_2:
        entity_id:
          - sensor.bom_gosford_max_temp_c_2
          - sensor.bom_gosford_min_temp_c_2
          - sensor.bom_gosford_chance_of_rain_2
          - sensor.bom_gosford_icon_2
        friendly_name_template: >
          {%- set date = as_timestamp(now()) + (2 * 86400 ) -%}
          {{ date | timestamp_custom("%A (%d/%m)") | replace("(0", "(") | replace("/0", "/") }}
        value_template: >
          {{states('sensor.bom_gosford_max_temp_c_2')|round(0)}}°/{{states('sensor.bom_gosford_min_temp_c_2')|round(0)}}°/{{states('sensor.bom_gosford_chance_of_rain_2')|round(0)}}%
        entity_picture_template: >-
          {{ '/local/icons/bom_icons/' ~ states('sensor.bom_gosford_icon_2') ~ '.png' }}

      bom_forecast_3:
        entity_id:
          - sensor.bom_gosford_max_temp_c_3
          - sensor.bom_gosford_min_temp_c_3
          - sensor.bom_gosford_chance_of_rain_3
          - sensor.bom_gosford_icon_3
        friendly_name_template: >
          {%- set date = as_timestamp(now()) + (3 * 86400 ) -%}
          {{ date | timestamp_custom("%A (%d/%m)") | replace("(0", "(") | replace("/0", "/") }}
        value_template: >
          {{states('sensor.bom_gosford_max_temp_c_3')|round(0)}}°/{{states('sensor.bom_gosford_min_temp_c_3')|round(0)}}°/{{states('sensor.bom_gosford_chance_of_rain_3')|round(0)}}%
        entity_picture_template: >-
          {{ '/local/icons/bom_icons/' ~ states('sensor.bom_gosford_icon_3') ~ '.png' }}

      bom_forecast_4:
        entity_id:
          - sensor.bom_gosford_max_temp_c_4
          - sensor.bom_gosford_min_temp_c_4
          - sensor.bom_gosford_chance_of_rain_4
          - sensor.bom_gosford_icon_4
        friendly_name_template: >
          {%- set date = as_timestamp(now()) + (4 * 86400 ) -%}
          {{ date | timestamp_custom("%A (%d/%m)") | replace("(0", "(") | replace("/0", "/") }}
        value_template: >
          {{states('sensor.bom_gosford_max_temp_c_4')|round(0)}}°/{{states('sensor.bom_gosford_min_temp_c_4')|round(0)}}°/{{states('sensor.bom_gosford_chance_of_rain_4')|round(0)}}%
        entity_picture_template: >-
          {{ '/local/icons/bom_icons/' ~ states('sensor.bom_gosford_icon_4') ~ '.png' }}

      bom_forecast_5:
        entity_id:
          - sensor.bom_gosford_max_temp_c_5
          - sensor.bom_gosford_min_temp_c_5
          - sensor.bom_gosford_chance_of_rain_5
          - sensor.bom_gosford_icon_5
        friendly_name_template: >
          {%- set date = as_timestamp(now()) + (5 * 86400 ) -%}
          {{ date | timestamp_custom("%A (%d/%m)") | replace("(0", "(") | replace("/0", "/") }}
        value_template: >
          {{states('sensor.bom_gosford_max_temp_c_5')|round(0)}}°/{{states('sensor.bom_gosford_min_temp_c_5')|round(0)}}°/{{states('sensor.bom_gosford_chance_of_rain_5')|round(0)}}%
        entity_picture_template: >-
          {{ '/local/icons/bom_icons/' ~ states('sensor.bom_gosford_icon_5') ~ '.png' }}

      bom_forecast_6:
        entity_id:
          - sensor.bom_gosford_max_temp_c_6
          - sensor.bom_gosford_min_temp_c_6
          - sensor.bom_gosford_chance_of_rain_6
          - sensor.bom_gosford_icon_6
        friendly_name_template: >
          {%- set date = as_timestamp(now()) + (6 * 86400 ) -%}
          {{ date | timestamp_custom("%A (%d/%m)") | replace("(0", "(") | replace("/0", "/") }}
        value_template: >
          {{states('sensor.bom_gosford_max_temp_c_6')|round(0)}}°/{{states('sensor.bom_gosford_min_temp_c_6')|round(0)}}°/{{states('sensor.bom_gosford_chance_of_rain_6')|round(0)}}%
        entity_picture_template: >-
          {{ '/local/icons/bom_icons/' ~ states('sensor.bom_gosford_icon_6') ~ '.png' }}

      bom_today_max:
        entity_id:
          - sensor.bom_gosford_max_temp_c_0
          - sensor.today_temp_bom_mean
        value_template: >
          {%- if states('sensor.bom_gosford_max_temp_c_0') == 'n/a' -%} 
            {{ state_attr('sensor.today_temp_bom_mean', 'max_value') }}
          {% else %}
            {{ states('sensor.bom_gosford_max_temp_c_0') }}
          {% endif %}
      bom_today_min:
        entity_id:
          - sensor.bom_gosford_min_temp_c_0
          - sensor.today_temp_bom_mean
        value_template: >
          {%- if states('sensor.bom_gosford_min_temp_c_0') == 'n/a' -%} 
            {{ state_attr('sensor.today_temp_bom_mean', 'min_value') }}
          {% else %}
            {{ states('sensor.bom_gosford_min_temp_c_0') }}
          {% endif %}

  - platform: statistics
    name: today_temp_bom
    sampling_size: 150
    entity_id: sensor.bom_gosford_air_temp_c
    max_age:
      hours: 24

automation:
- alias: 'Update BOM Icons'
  trigger:
    - event: start
      platform: homeassistant
    - platform: time
      at: '18:01:00'
  action:
    - service: homeassistant.update_entity
      entity_id: sensor.bom_forecast_0, sensor.bom_forecast_1, sensor.bom_forecast_2, sensor.bom_forecast_3, sensor.bom_forecast_4, sensor.bom_forecast_5, sensor.bom_forecast_6
